// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.21.2
// source: dataserver.proto

package dataserver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SplitShardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SplitShardRequest) Reset() {
	*x = SplitShardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataserver_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SplitShardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SplitShardRequest) ProtoMessage() {}

func (x *SplitShardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataserver_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SplitShardRequest.ProtoReflect.Descriptor instead.
func (*SplitShardRequest) Descriptor() ([]byte, []int) {
	return file_dataserver_proto_rawDescGZIP(), []int{0}
}

type SplitShardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SplitShardResponse) Reset() {
	*x = SplitShardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataserver_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SplitShardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SplitShardResponse) ProtoMessage() {}

func (x *SplitShardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataserver_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SplitShardResponse.ProtoReflect.Descriptor instead.
func (*SplitShardResponse) Descriptor() ([]byte, []int) {
	return file_dataserver_proto_rawDescGZIP(), []int{1}
}

type MergeShardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MergeShardRequest) Reset() {
	*x = MergeShardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataserver_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MergeShardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeShardRequest) ProtoMessage() {}

func (x *MergeShardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataserver_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeShardRequest.ProtoReflect.Descriptor instead.
func (*MergeShardRequest) Descriptor() ([]byte, []int) {
	return file_dataserver_proto_rawDescGZIP(), []int{2}
}

type MergeShardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MergeShardResponse) Reset() {
	*x = MergeShardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataserver_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MergeShardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeShardResponse) ProtoMessage() {}

func (x *MergeShardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataserver_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeShardResponse.ProtoReflect.Descriptor instead.
func (*MergeShardResponse) Descriptor() ([]byte, []int) {
	return file_dataserver_proto_rawDescGZIP(), []int{3}
}

type CreateShardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShardId         uint64                 `protobuf:"varint,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	StorageId       uint64                 `protobuf:"varint,2,opt,name=storage_id,json=storageId,proto3" json:"storage_id,omitempty"`
	CreateTs        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=create_ts,json=createTs,proto3" json:"create_ts,omitempty"`
	Replicates      []string               `protobuf:"bytes,4,rep,name=replicates,proto3" json:"replicates,omitempty"`
	ReplicaUpdateTs *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=replica_update_ts,json=replicaUpdateTs,proto3" json:"replica_update_ts,omitempty"`
	Leader          string                 `protobuf:"bytes,6,opt,name=leader,proto3" json:"leader,omitempty"`
	LeaderChangeTs  *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=leader_change_ts,json=leaderChangeTs,proto3" json:"leader_change_ts,omitempty"`
}

func (x *CreateShardRequest) Reset() {
	*x = CreateShardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataserver_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateShardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShardRequest) ProtoMessage() {}

func (x *CreateShardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataserver_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShardRequest.ProtoReflect.Descriptor instead.
func (*CreateShardRequest) Descriptor() ([]byte, []int) {
	return file_dataserver_proto_rawDescGZIP(), []int{4}
}

func (x *CreateShardRequest) GetShardId() uint64 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *CreateShardRequest) GetStorageId() uint64 {
	if x != nil {
		return x.StorageId
	}
	return 0
}

func (x *CreateShardRequest) GetCreateTs() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTs
	}
	return nil
}

func (x *CreateShardRequest) GetReplicates() []string {
	if x != nil {
		return x.Replicates
	}
	return nil
}

func (x *CreateShardRequest) GetReplicaUpdateTs() *timestamppb.Timestamp {
	if x != nil {
		return x.ReplicaUpdateTs
	}
	return nil
}

func (x *CreateShardRequest) GetLeader() string {
	if x != nil {
		return x.Leader
	}
	return ""
}

func (x *CreateShardRequest) GetLeaderChangeTs() *timestamppb.Timestamp {
	if x != nil {
		return x.LeaderChangeTs
	}
	return nil
}

type CreateShardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateShardResponse) Reset() {
	*x = CreateShardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataserver_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateShardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShardResponse) ProtoMessage() {}

func (x *CreateShardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataserver_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShardResponse.ProtoReflect.Descriptor instead.
func (*CreateShardResponse) Descriptor() ([]byte, []int) {
	return file_dataserver_proto_rawDescGZIP(), []int{5}
}

type DeleteShardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShardId uint64 `protobuf:"varint,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
}

func (x *DeleteShardRequest) Reset() {
	*x = DeleteShardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataserver_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteShardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShardRequest) ProtoMessage() {}

func (x *DeleteShardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataserver_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShardRequest.ProtoReflect.Descriptor instead.
func (*DeleteShardRequest) Descriptor() ([]byte, []int) {
	return file_dataserver_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteShardRequest) GetShardId() uint64 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

type DeleteShardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteShardResponse) Reset() {
	*x = DeleteShardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataserver_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteShardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShardResponse) ProtoMessage() {}

func (x *DeleteShardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataserver_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShardResponse.ProtoReflect.Descriptor instead.
func (*DeleteShardResponse) Descriptor() ([]byte, []int) {
	return file_dataserver_proto_rawDescGZIP(), []int{7}
}

type PullShardDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PullShardDataRequest) Reset() {
	*x = PullShardDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataserver_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullShardDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullShardDataRequest) ProtoMessage() {}

func (x *PullShardDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataserver_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullShardDataRequest.ProtoReflect.Descriptor instead.
func (*PullShardDataRequest) Descriptor() ([]byte, []int) {
	return file_dataserver_proto_rawDescGZIP(), []int{8}
}

type PullShardDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PullShardDataResponse) Reset() {
	*x = PullShardDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataserver_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullShardDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullShardDataResponse) ProtoMessage() {}

func (x *PullShardDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataserver_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullShardDataResponse.ProtoReflect.Descriptor instead.
func (*PullShardDataResponse) Descriptor() ([]byte, []int) {
	return file_dataserver_proto_rawDescGZIP(), []int{9}
}

type TransferShardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TransferShardRequest) Reset() {
	*x = TransferShardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataserver_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransferShardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferShardRequest) ProtoMessage() {}

func (x *TransferShardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataserver_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferShardRequest.ProtoReflect.Descriptor instead.
func (*TransferShardRequest) Descriptor() ([]byte, []int) {
	return file_dataserver_proto_rawDescGZIP(), []int{10}
}

type TransferShardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TransferShardResponse) Reset() {
	*x = TransferShardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataserver_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransferShardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferShardResponse) ProtoMessage() {}

func (x *TransferShardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataserver_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferShardResponse.ProtoReflect.Descriptor instead.
func (*TransferShardResponse) Descriptor() ([]byte, []int) {
	return file_dataserver_proto_rawDescGZIP(), []int{11}
}

type AddShardReplicaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddShardReplicaRequest) Reset() {
	*x = AddShardReplicaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataserver_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddShardReplicaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddShardReplicaRequest) ProtoMessage() {}

func (x *AddShardReplicaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataserver_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddShardReplicaRequest.ProtoReflect.Descriptor instead.
func (*AddShardReplicaRequest) Descriptor() ([]byte, []int) {
	return file_dataserver_proto_rawDescGZIP(), []int{12}
}

type AddShardReplicaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddShardReplicaResponse) Reset() {
	*x = AddShardReplicaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataserver_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddShardReplicaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddShardReplicaResponse) ProtoMessage() {}

func (x *AddShardReplicaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataserver_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddShardReplicaResponse.ProtoReflect.Descriptor instead.
func (*AddShardReplicaResponse) Descriptor() ([]byte, []int) {
	return file_dataserver_proto_rawDescGZIP(), []int{13}
}

type DeleteShardReplicaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteShardReplicaRequest) Reset() {
	*x = DeleteShardReplicaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataserver_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteShardReplicaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShardReplicaRequest) ProtoMessage() {}

func (x *DeleteShardReplicaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataserver_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShardReplicaRequest.ProtoReflect.Descriptor instead.
func (*DeleteShardReplicaRequest) Descriptor() ([]byte, []int) {
	return file_dataserver_proto_rawDescGZIP(), []int{14}
}

type DeleteShardReplicaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteShardReplicaResponse) Reset() {
	*x = DeleteShardReplicaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataserver_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteShardReplicaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShardReplicaResponse) ProtoMessage() {}

func (x *DeleteShardReplicaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataserver_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShardReplicaResponse.ProtoReflect.Descriptor instead.
func (*DeleteShardReplicaResponse) Descriptor() ([]byte, []int) {
	return file_dataserver_proto_rawDescGZIP(), []int{15}
}

type TransferShardLeaderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShardId    uint64   `protobuf:"varint,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Replicates []string `protobuf:"bytes,2,rep,name=replicates,proto3" json:"replicates,omitempty"`
}

func (x *TransferShardLeaderRequest) Reset() {
	*x = TransferShardLeaderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataserver_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransferShardLeaderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferShardLeaderRequest) ProtoMessage() {}

func (x *TransferShardLeaderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataserver_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferShardLeaderRequest.ProtoReflect.Descriptor instead.
func (*TransferShardLeaderRequest) Descriptor() ([]byte, []int) {
	return file_dataserver_proto_rawDescGZIP(), []int{16}
}

func (x *TransferShardLeaderRequest) GetShardId() uint64 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *TransferShardLeaderRequest) GetReplicates() []string {
	if x != nil {
		return x.Replicates
	}
	return nil
}

type TransferShardLeaderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TransferShardLeaderResponse) Reset() {
	*x = TransferShardLeaderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataserver_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransferShardLeaderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferShardLeaderResponse) ProtoMessage() {}

func (x *TransferShardLeaderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataserver_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferShardLeaderResponse.ProtoReflect.Descriptor instead.
func (*TransferShardLeaderResponse) Descriptor() ([]byte, []int) {
	return file_dataserver_proto_rawDescGZIP(), []int{17}
}

type LockShardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LockShardRequest) Reset() {
	*x = LockShardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataserver_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LockShardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockShardRequest) ProtoMessage() {}

func (x *LockShardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataserver_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockShardRequest.ProtoReflect.Descriptor instead.
func (*LockShardRequest) Descriptor() ([]byte, []int) {
	return file_dataserver_proto_rawDescGZIP(), []int{18}
}

type LockShardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LockShardResponse) Reset() {
	*x = LockShardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataserver_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LockShardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockShardResponse) ProtoMessage() {}

func (x *LockShardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataserver_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockShardResponse.ProtoReflect.Descriptor instead.
func (*LockShardResponse) Descriptor() ([]byte, []int) {
	return file_dataserver_proto_rawDescGZIP(), []int{19}
}

type UnlockShardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UnlockShardRequest) Reset() {
	*x = UnlockShardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataserver_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnlockShardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockShardRequest) ProtoMessage() {}

func (x *UnlockShardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataserver_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockShardRequest.ProtoReflect.Descriptor instead.
func (*UnlockShardRequest) Descriptor() ([]byte, []int) {
	return file_dataserver_proto_rawDescGZIP(), []int{20}
}

type UnlockShardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UnlockShardResponse) Reset() {
	*x = UnlockShardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataserver_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnlockShardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockShardResponse) ProtoMessage() {}

func (x *UnlockShardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataserver_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockShardResponse.ProtoReflect.Descriptor instead.
func (*UnlockShardResponse) Descriptor() ([]byte, []int) {
	return file_dataserver_proto_rawDescGZIP(), []int{21}
}

type ShardReadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShardId uint64 `protobuf:"varint,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Key     []byte `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *ShardReadRequest) Reset() {
	*x = ShardReadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataserver_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShardReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardReadRequest) ProtoMessage() {}

func (x *ShardReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataserver_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardReadRequest.ProtoReflect.Descriptor instead.
func (*ShardReadRequest) Descriptor() ([]byte, []int) {
	return file_dataserver_proto_rawDescGZIP(), []int{22}
}

func (x *ShardReadRequest) GetShardId() uint64 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *ShardReadRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type ShardReadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ShardReadResponse) Reset() {
	*x = ShardReadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataserver_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShardReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardReadResponse) ProtoMessage() {}

func (x *ShardReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataserver_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardReadResponse.ProtoReflect.Descriptor instead.
func (*ShardReadResponse) Descriptor() ([]byte, []int) {
	return file_dataserver_proto_rawDescGZIP(), []int{23}
}

func (x *ShardReadResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type ShardWriteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShardId uint64 `protobuf:"varint,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Key     []byte `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value   []byte `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ShardWriteRequest) Reset() {
	*x = ShardWriteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataserver_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShardWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardWriteRequest) ProtoMessage() {}

func (x *ShardWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataserver_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardWriteRequest.ProtoReflect.Descriptor instead.
func (*ShardWriteRequest) Descriptor() ([]byte, []int) {
	return file_dataserver_proto_rawDescGZIP(), []int{24}
}

func (x *ShardWriteRequest) GetShardId() uint64 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *ShardWriteRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ShardWriteRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type ShardWriteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ShardWriteResponse) Reset() {
	*x = ShardWriteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataserver_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShardWriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardWriteResponse) ProtoMessage() {}

func (x *ShardWriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataserver_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardWriteResponse.ProtoReflect.Descriptor instead.
func (*ShardWriteResponse) Descriptor() ([]byte, []int) {
	return file_dataserver_proto_rawDescGZIP(), []int{25}
}

type ShardAppendLogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShardId        uint64                         `protobuf:"varint,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	LeaderChangeTs *timestamppb.Timestamp         `protobuf:"bytes,2,opt,name=leader_change_ts,json=leaderChangeTs,proto3" json:"leader_change_ts,omitempty"`
	Entries        []*ShardAppendLogRequest_Entry `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *ShardAppendLogRequest) Reset() {
	*x = ShardAppendLogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataserver_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShardAppendLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardAppendLogRequest) ProtoMessage() {}

func (x *ShardAppendLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataserver_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardAppendLogRequest.ProtoReflect.Descriptor instead.
func (*ShardAppendLogRequest) Descriptor() ([]byte, []int) {
	return file_dataserver_proto_rawDescGZIP(), []int{26}
}

func (x *ShardAppendLogRequest) GetShardId() uint64 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *ShardAppendLogRequest) GetLeaderChangeTs() *timestamppb.Timestamp {
	if x != nil {
		return x.LeaderChangeTs
	}
	return nil
}

func (x *ShardAppendLogRequest) GetEntries() []*ShardAppendLogRequest_Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type ShardAppendLogResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsOldLeader      bool   `protobuf:"varint,1,opt,name=is_old_leader,json=isOldLeader,proto3" json:"is_old_leader,omitempty"`
	LastAppliedIndex uint64 `protobuf:"varint,2,opt,name=last_applied_index,json=lastAppliedIndex,proto3" json:"last_applied_index,omitempty"`
}

func (x *ShardAppendLogResponse) Reset() {
	*x = ShardAppendLogResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataserver_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShardAppendLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardAppendLogResponse) ProtoMessage() {}

func (x *ShardAppendLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataserver_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardAppendLogResponse.ProtoReflect.Descriptor instead.
func (*ShardAppendLogResponse) Descriptor() ([]byte, []int) {
	return file_dataserver_proto_rawDescGZIP(), []int{27}
}

func (x *ShardAppendLogResponse) GetIsOldLeader() bool {
	if x != nil {
		return x.IsOldLeader
	}
	return false
}

func (x *ShardAppendLogResponse) GetLastAppliedIndex() uint64 {
	if x != nil {
		return x.LastAppliedIndex
	}
	return 0
}

type ShardInstallSnapshotRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShardId   uint64 `protobuf:"varint,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	DataPiece []byte `protobuf:"bytes,2,opt,name=data_piece,json=dataPiece,proto3" json:"data_piece,omitempty"`
}

func (x *ShardInstallSnapshotRequest) Reset() {
	*x = ShardInstallSnapshotRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataserver_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShardInstallSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardInstallSnapshotRequest) ProtoMessage() {}

func (x *ShardInstallSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataserver_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardInstallSnapshotRequest.ProtoReflect.Descriptor instead.
func (*ShardInstallSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_dataserver_proto_rawDescGZIP(), []int{28}
}

func (x *ShardInstallSnapshotRequest) GetShardId() uint64 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *ShardInstallSnapshotRequest) GetDataPiece() []byte {
	if x != nil {
		return x.DataPiece
	}
	return nil
}

type ShardInstallSnapshotResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ShardInstallSnapshotResponse) Reset() {
	*x = ShardInstallSnapshotResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataserver_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShardInstallSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardInstallSnapshotResponse) ProtoMessage() {}

func (x *ShardInstallSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataserver_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardInstallSnapshotResponse.ProtoReflect.Descriptor instead.
func (*ShardInstallSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_dataserver_proto_rawDescGZIP(), []int{29}
}

type ShardWriteReplicaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ShardWriteReplicaRequest) Reset() {
	*x = ShardWriteReplicaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataserver_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShardWriteReplicaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardWriteReplicaRequest) ProtoMessage() {}

func (x *ShardWriteReplicaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataserver_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardWriteReplicaRequest.ProtoReflect.Descriptor instead.
func (*ShardWriteReplicaRequest) Descriptor() ([]byte, []int) {
	return file_dataserver_proto_rawDescGZIP(), []int{30}
}

type ShardWriteReplicaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ShardWriteReplicaResponse) Reset() {
	*x = ShardWriteReplicaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataserver_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShardWriteReplicaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardWriteReplicaResponse) ProtoMessage() {}

func (x *ShardWriteReplicaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataserver_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardWriteReplicaResponse.ProtoReflect.Descriptor instead.
func (*ShardWriteReplicaResponse) Descriptor() ([]byte, []int) {
	return file_dataserver_proto_rawDescGZIP(), []int{31}
}

type ShardRepairRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ShardRepairRequest) Reset() {
	*x = ShardRepairRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataserver_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShardRepairRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardRepairRequest) ProtoMessage() {}

func (x *ShardRepairRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataserver_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardRepairRequest.ProtoReflect.Descriptor instead.
func (*ShardRepairRequest) Descriptor() ([]byte, []int) {
	return file_dataserver_proto_rawDescGZIP(), []int{32}
}

type ShardRepairResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ShardRepairResponse) Reset() {
	*x = ShardRepairResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataserver_proto_msgTypes[33]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShardRepairResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardRepairResponse) ProtoMessage() {}

func (x *ShardRepairResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataserver_proto_msgTypes[33]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardRepairResponse.ProtoReflect.Descriptor instead.
func (*ShardRepairResponse) Descriptor() ([]byte, []int) {
	return file_dataserver_proto_rawDescGZIP(), []int{33}
}

type DataServerJoinRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DataServerJoinRequest) Reset() {
	*x = DataServerJoinRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataserver_proto_msgTypes[34]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataServerJoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataServerJoinRequest) ProtoMessage() {}

func (x *DataServerJoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataserver_proto_msgTypes[34]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataServerJoinRequest.ProtoReflect.Descriptor instead.
func (*DataServerJoinRequest) Descriptor() ([]byte, []int) {
	return file_dataserver_proto_rawDescGZIP(), []int{34}
}

type DataServerJoinResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DataServerJoinResponse) Reset() {
	*x = DataServerJoinResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataserver_proto_msgTypes[35]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataServerJoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataServerJoinResponse) ProtoMessage() {}

func (x *DataServerJoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataserver_proto_msgTypes[35]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataServerJoinResponse.ProtoReflect.Descriptor instead.
func (*DataServerJoinResponse) Descriptor() ([]byte, []int) {
	return file_dataserver_proto_rawDescGZIP(), []int{35}
}

type DataServerLeaveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DataServerLeaveRequest) Reset() {
	*x = DataServerLeaveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataserver_proto_msgTypes[36]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataServerLeaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataServerLeaveRequest) ProtoMessage() {}

func (x *DataServerLeaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataserver_proto_msgTypes[36]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataServerLeaveRequest.ProtoReflect.Descriptor instead.
func (*DataServerLeaveRequest) Descriptor() ([]byte, []int) {
	return file_dataserver_proto_rawDescGZIP(), []int{36}
}

type DataServerLeaveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DataServerLeaveResponse) Reset() {
	*x = DataServerLeaveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataserver_proto_msgTypes[37]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataServerLeaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataServerLeaveResponse) ProtoMessage() {}

func (x *DataServerLeaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataserver_proto_msgTypes[37]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataServerLeaveResponse.ProtoReflect.Descriptor instead.
func (*DataServerLeaveResponse) Descriptor() ([]byte, []int) {
	return file_dataserver_proto_rawDescGZIP(), []int{37}
}

type ShardAppendLogRequest_Entry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Op    string `protobuf:"bytes,1,opt,name=op,proto3" json:"op,omitempty"`
	Index uint64 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Key   []byte `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ShardAppendLogRequest_Entry) Reset() {
	*x = ShardAppendLogRequest_Entry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataserver_proto_msgTypes[38]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShardAppendLogRequest_Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardAppendLogRequest_Entry) ProtoMessage() {}

func (x *ShardAppendLogRequest_Entry) ProtoReflect() protoreflect.Message {
	mi := &file_dataserver_proto_msgTypes[38]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardAppendLogRequest_Entry.ProtoReflect.Descriptor instead.
func (*ShardAppendLogRequest_Entry) Descriptor() ([]byte, []int) {
	return file_dataserver_proto_rawDescGZIP(), []int{26, 0}
}

func (x *ShardAppendLogRequest_Entry) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *ShardAppendLogRequest_Entry) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ShardAppendLogRequest_Entry) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ShardAppendLogRequest_Entry) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_dataserver_proto protoreflect.FileDescriptor

var file_dataserver_proto_rawDesc = []byte{
	0x0a, 0x10, 0x64, 0x61, 0x74, 0x61, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x12, 0x62, 0x65, 0x64, 0x72, 0x6f, 0x63, 0x6b, 0x2e, 0x64, 0x61, 0x74, 0x61,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x13, 0x0a, 0x11, 0x53, 0x70, 0x6c, 0x69, 0x74, 0x53, 0x68, 0x61,
	0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x14, 0x0a, 0x12, 0x53, 0x70, 0x6c,
	0x69, 0x74, 0x53, 0x68, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x13, 0x0a, 0x11, 0x4d, 0x65, 0x72, 0x67, 0x65, 0x53, 0x68, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x14, 0x0a, 0x12, 0x4d, 0x65, 0x72, 0x67, 0x65, 0x53, 0x68, 0x61,
	0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xcd, 0x02, 0x0a, 0x12, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x68, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x68, 0x61, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x07, 0x73, 0x68, 0x61, 0x72, 0x64, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a,
	0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x09, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x37, 0x0a, 0x09, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x08, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x54, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74,
	0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63,
	0x61, 0x74, 0x65, 0x73, 0x12, 0x46, 0x0a, 0x11, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x5f,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0f, 0x72, 0x65, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x12, 0x44, 0x0a, 0x10, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x5f, 0x63,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x74, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0e, 0x6c, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x73, 0x22, 0x15, 0x0a, 0x13, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x53, 0x68, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x2f, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x68, 0x61, 0x72, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x68, 0x61, 0x72, 0x64,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x73, 0x68, 0x61, 0x72, 0x64,
	0x49, 0x64, 0x22, 0x15, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x68, 0x61, 0x72,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x16, 0x0a, 0x14, 0x50, 0x75, 0x6c,
	0x6c, 0x53, 0x68, 0x61, 0x72, 0x64, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x17, 0x0a, 0x15, 0x50, 0x75, 0x6c, 0x6c, 0x53, 0x68, 0x61, 0x72, 0x64, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x16, 0x0a, 0x14, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x53, 0x68, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x17, 0x0a, 0x15, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x53, 0x68,
	0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x18, 0x0a, 0x16, 0x41,
	0x64, 0x64, 0x53, 0x68, 0x61, 0x72, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x19, 0x0a, 0x17, 0x41, 0x64, 0x64, 0x53, 0x68, 0x61, 0x72,
	0x64, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x1b, 0x0a, 0x19, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x68, 0x61, 0x72, 0x64, 0x52,
	0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1c, 0x0a,
	0x1a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x68, 0x61, 0x72, 0x64, 0x52, 0x65, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x57, 0x0a, 0x1a, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x53, 0x68, 0x61, 0x72, 0x64, 0x4c, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x68, 0x61,
	0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x73, 0x68, 0x61,
	0x72, 0x64, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63,
	0x61, 0x74, 0x65, 0x73, 0x22, 0x1d, 0x0a, 0x1b, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72,
	0x53, 0x68, 0x61, 0x72, 0x64, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x12, 0x0a, 0x10, 0x4c, 0x6f, 0x63, 0x6b, 0x53, 0x68, 0x61, 0x72, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x13, 0x0a, 0x11, 0x4c, 0x6f, 0x63, 0x6b, 0x53,
	0x68, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x14, 0x0a, 0x12,
	0x55, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x68, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x15, 0x0a, 0x13, 0x55, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x68, 0x61, 0x72,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x3f, 0x0a, 0x10, 0x53, 0x68, 0x61,
	0x72, 0x64, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a,
	0x08, 0x73, 0x68, 0x61, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x07, 0x73, 0x68, 0x61, 0x72, 0x64, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x29, 0x0a, 0x11, 0x53, 0x68,
	0x61, 0x72, 0x64, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x56, 0x0a, 0x11, 0x53, 0x68, 0x61, 0x72, 0x64, 0x57, 0x72,
	0x69, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x68,
	0x61, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x73, 0x68,
	0x61, 0x72, 0x64, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x14, 0x0a,
	0x12, 0x53, 0x68, 0x61, 0x72, 0x64, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x9a, 0x02, 0x0a, 0x15, 0x53, 0x68, 0x61, 0x72, 0x64, 0x41, 0x70, 0x70,
	0x65, 0x6e, 0x64, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a,
	0x08, 0x73, 0x68, 0x61, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x07, 0x73, 0x68, 0x61, 0x72, 0x64, 0x49, 0x64, 0x12, 0x44, 0x0a, 0x10, 0x6c, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0e,
	0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x73, 0x12, 0x49,
	0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x2f, 0x2e, 0x62, 0x65, 0x64, 0x72, 0x6f, 0x63, 0x6b, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x64, 0x41, 0x70, 0x70, 0x65, 0x6e, 0x64,
	0x4c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x1a, 0x55, 0x0a, 0x05, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x6f, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x6a, 0x0a, 0x16, 0x53, 0x68, 0x61, 0x72, 0x64, 0x41, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x4c,
	0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x0d, 0x69, 0x73,
	0x5f, 0x6f, 0x6c, 0x64, 0x5f, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0b, 0x69, 0x73, 0x4f, 0x6c, 0x64, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x2c,
	0x0a, 0x12, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x64, 0x5f, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x10, 0x6c, 0x61, 0x73, 0x74,
	0x41, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x64, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x57, 0x0a, 0x1b,
	0x53, 0x68, 0x61, 0x72, 0x64, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x53, 0x6e, 0x61, 0x70,
	0x73, 0x68, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x73,
	0x68, 0x61, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x73,
	0x68, 0x61, 0x72, 0x64, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x70,
	0x69, 0x65, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x64, 0x61, 0x74, 0x61,
	0x50, 0x69, 0x65, 0x63, 0x65, 0x22, 0x1e, 0x0a, 0x1c, 0x53, 0x68, 0x61, 0x72, 0x64, 0x49, 0x6e,
	0x73, 0x74, 0x61, 0x6c, 0x6c, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1a, 0x0a, 0x18, 0x53, 0x68, 0x61, 0x72, 0x64, 0x57, 0x72,
	0x69, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x1b, 0x0a, 0x19, 0x53, 0x68, 0x61, 0x72, 0x64, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x14,
	0x0a, 0x12, 0x53, 0x68, 0x61, 0x72, 0x64, 0x52, 0x65, 0x70, 0x61, 0x69, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x15, 0x0a, 0x13, 0x53, 0x68, 0x61, 0x72, 0x64, 0x52, 0x65, 0x70,
	0x61, 0x69, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x17, 0x0a, 0x15, 0x44,
	0x61, 0x74, 0x61, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x18, 0x0a, 0x16, 0x44, 0x61, 0x74, 0x61, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x18,
	0x0a, 0x16, 0x44, 0x61, 0x74, 0x61, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4c, 0x65, 0x61, 0x76,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x19, 0x0a, 0x17, 0x44, 0x61, 0x74, 0x61,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x32, 0xd1, 0x05, 0x0a, 0x0b, 0x44, 0x61, 0x74, 0x61, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x5e, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x68, 0x61,
	0x72, 0x64, 0x12, 0x26, 0x2e, 0x62, 0x65, 0x64, 0x72, 0x6f, 0x63, 0x6b, 0x2e, 0x64, 0x61, 0x74,
	0x61, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x68,
	0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x62, 0x65, 0x64,
	0x72, 0x6f, 0x63, 0x6b, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x68, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x68, 0x61,
	0x72, 0x64, 0x12, 0x26, 0x2e, 0x62, 0x65, 0x64, 0x72, 0x6f, 0x63, 0x6b, 0x2e, 0x64, 0x61, 0x74,
	0x61, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x68,
	0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x12, 0x76, 0x0a, 0x13, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x53, 0x68,
	0x61, 0x72, 0x64, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x2e, 0x2e, 0x62, 0x65, 0x64, 0x72,
	0x6f, 0x63, 0x6b, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x53, 0x68, 0x61, 0x72, 0x64, 0x4c, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2f, 0x2e, 0x62, 0x65, 0x64, 0x72,
	0x6f, 0x63, 0x6b, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x53, 0x68, 0x61, 0x72, 0x64, 0x4c, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x58, 0x0a, 0x09, 0x53, 0x68,
	0x61, 0x72, 0x64, 0x52, 0x65, 0x61, 0x64, 0x12, 0x24, 0x2e, 0x62, 0x65, 0x64, 0x72, 0x6f, 0x63,
	0x6b, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x53, 0x68, 0x61,
	0x72, 0x64, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e,
	0x62, 0x65, 0x64, 0x72, 0x6f, 0x63, 0x6b, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x64, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5b, 0x0a, 0x0a, 0x53, 0x68, 0x61, 0x72, 0x64, 0x57, 0x72, 0x69,
	0x74, 0x65, 0x12, 0x25, 0x2e, 0x62, 0x65, 0x64, 0x72, 0x6f, 0x63, 0x6b, 0x2e, 0x64, 0x61, 0x74,
	0x61, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x64, 0x57, 0x72, 0x69,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x62, 0x65, 0x64, 0x72,
	0x6f, 0x63, 0x6b, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x53,
	0x68, 0x61, 0x72, 0x64, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x67, 0x0a, 0x0e, 0x53, 0x68, 0x61, 0x72, 0x64, 0x41, 0x70, 0x70, 0x65, 0x6e, 0x64,
	0x4c, 0x6f, 0x67, 0x12, 0x29, 0x2e, 0x62, 0x65, 0x64, 0x72, 0x6f, 0x63, 0x6b, 0x2e, 0x64, 0x61,
	0x74, 0x61, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x64, 0x41, 0x70,
	0x70, 0x65, 0x6e, 0x64, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a,
	0x2e, 0x62, 0x65, 0x64, 0x72, 0x6f, 0x63, 0x6b, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x64, 0x41, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x4c,
	0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x7b, 0x0a, 0x14, 0x53, 0x68,
	0x61, 0x72, 0x64, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68,
	0x6f, 0x74, 0x12, 0x2f, 0x2e, 0x62, 0x65, 0x64, 0x72, 0x6f, 0x63, 0x6b, 0x2e, 0x64, 0x61, 0x74,
	0x61, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x64, 0x49, 0x6e, 0x73,
	0x74, 0x61, 0x6c, 0x6c, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x30, 0x2e, 0x62, 0x65, 0x64, 0x72, 0x6f, 0x63, 0x6b, 0x2e, 0x64, 0x61,
	0x74, 0x61, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x64, 0x49, 0x6e,
	0x73, 0x74, 0x61, 0x6c, 0x6c, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x42, 0x31, 0x5a, 0x2c, 0x73, 0x72, 0x2e, 0x68, 0x74,
	0x2f, 0x6d, 0x6f, 0x79, 0x61, 0x6e, 0x68, 0x61, 0x6f, 0x2f, 0x62, 0x65, 0x64, 0x72, 0x6f, 0x63,
	0x6b, 0x2d, 0x6d, 0x65, 0x74, 0x61, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x64, 0x61, 0x74,
	0x61, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x80, 0x01, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_dataserver_proto_rawDescOnce sync.Once
	file_dataserver_proto_rawDescData = file_dataserver_proto_rawDesc
)

func file_dataserver_proto_rawDescGZIP() []byte {
	file_dataserver_proto_rawDescOnce.Do(func() {
		file_dataserver_proto_rawDescData = protoimpl.X.CompressGZIP(file_dataserver_proto_rawDescData)
	})
	return file_dataserver_proto_rawDescData
}

var file_dataserver_proto_msgTypes = make([]protoimpl.MessageInfo, 39)
var file_dataserver_proto_goTypes = []interface{}{
	(*SplitShardRequest)(nil),            // 0: bedrock.dataserver.SplitShardRequest
	(*SplitShardResponse)(nil),           // 1: bedrock.dataserver.SplitShardResponse
	(*MergeShardRequest)(nil),            // 2: bedrock.dataserver.MergeShardRequest
	(*MergeShardResponse)(nil),           // 3: bedrock.dataserver.MergeShardResponse
	(*CreateShardRequest)(nil),           // 4: bedrock.dataserver.CreateShardRequest
	(*CreateShardResponse)(nil),          // 5: bedrock.dataserver.CreateShardResponse
	(*DeleteShardRequest)(nil),           // 6: bedrock.dataserver.DeleteShardRequest
	(*DeleteShardResponse)(nil),          // 7: bedrock.dataserver.DeleteShardResponse
	(*PullShardDataRequest)(nil),         // 8: bedrock.dataserver.PullShardDataRequest
	(*PullShardDataResponse)(nil),        // 9: bedrock.dataserver.PullShardDataResponse
	(*TransferShardRequest)(nil),         // 10: bedrock.dataserver.TransferShardRequest
	(*TransferShardResponse)(nil),        // 11: bedrock.dataserver.TransferShardResponse
	(*AddShardReplicaRequest)(nil),       // 12: bedrock.dataserver.AddShardReplicaRequest
	(*AddShardReplicaResponse)(nil),      // 13: bedrock.dataserver.AddShardReplicaResponse
	(*DeleteShardReplicaRequest)(nil),    // 14: bedrock.dataserver.DeleteShardReplicaRequest
	(*DeleteShardReplicaResponse)(nil),   // 15: bedrock.dataserver.DeleteShardReplicaResponse
	(*TransferShardLeaderRequest)(nil),   // 16: bedrock.dataserver.TransferShardLeaderRequest
	(*TransferShardLeaderResponse)(nil),  // 17: bedrock.dataserver.TransferShardLeaderResponse
	(*LockShardRequest)(nil),             // 18: bedrock.dataserver.LockShardRequest
	(*LockShardResponse)(nil),            // 19: bedrock.dataserver.LockShardResponse
	(*UnlockShardRequest)(nil),           // 20: bedrock.dataserver.UnlockShardRequest
	(*UnlockShardResponse)(nil),          // 21: bedrock.dataserver.UnlockShardResponse
	(*ShardReadRequest)(nil),             // 22: bedrock.dataserver.ShardReadRequest
	(*ShardReadResponse)(nil),            // 23: bedrock.dataserver.ShardReadResponse
	(*ShardWriteRequest)(nil),            // 24: bedrock.dataserver.ShardWriteRequest
	(*ShardWriteResponse)(nil),           // 25: bedrock.dataserver.ShardWriteResponse
	(*ShardAppendLogRequest)(nil),        // 26: bedrock.dataserver.ShardAppendLogRequest
	(*ShardAppendLogResponse)(nil),       // 27: bedrock.dataserver.ShardAppendLogResponse
	(*ShardInstallSnapshotRequest)(nil),  // 28: bedrock.dataserver.ShardInstallSnapshotRequest
	(*ShardInstallSnapshotResponse)(nil), // 29: bedrock.dataserver.ShardInstallSnapshotResponse
	(*ShardWriteReplicaRequest)(nil),     // 30: bedrock.dataserver.ShardWriteReplicaRequest
	(*ShardWriteReplicaResponse)(nil),    // 31: bedrock.dataserver.ShardWriteReplicaResponse
	(*ShardRepairRequest)(nil),           // 32: bedrock.dataserver.ShardRepairRequest
	(*ShardRepairResponse)(nil),          // 33: bedrock.dataserver.ShardRepairResponse
	(*DataServerJoinRequest)(nil),        // 34: bedrock.dataserver.DataServerJoinRequest
	(*DataServerJoinResponse)(nil),       // 35: bedrock.dataserver.DataServerJoinResponse
	(*DataServerLeaveRequest)(nil),       // 36: bedrock.dataserver.DataServerLeaveRequest
	(*DataServerLeaveResponse)(nil),      // 37: bedrock.dataserver.DataServerLeaveResponse
	(*ShardAppendLogRequest_Entry)(nil),  // 38: bedrock.dataserver.ShardAppendLogRequest.Entry
	(*timestamppb.Timestamp)(nil),        // 39: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                // 40: google.protobuf.Empty
}
var file_dataserver_proto_depIdxs = []int32{
	39, // 0: bedrock.dataserver.CreateShardRequest.create_ts:type_name -> google.protobuf.Timestamp
	39, // 1: bedrock.dataserver.CreateShardRequest.replica_update_ts:type_name -> google.protobuf.Timestamp
	39, // 2: bedrock.dataserver.CreateShardRequest.leader_change_ts:type_name -> google.protobuf.Timestamp
	39, // 3: bedrock.dataserver.ShardAppendLogRequest.leader_change_ts:type_name -> google.protobuf.Timestamp
	38, // 4: bedrock.dataserver.ShardAppendLogRequest.entries:type_name -> bedrock.dataserver.ShardAppendLogRequest.Entry
	4,  // 5: bedrock.dataserver.DataService.CreateShard:input_type -> bedrock.dataserver.CreateShardRequest
	6,  // 6: bedrock.dataserver.DataService.DeleteShard:input_type -> bedrock.dataserver.DeleteShardRequest
	16, // 7: bedrock.dataserver.DataService.TransferShardLeader:input_type -> bedrock.dataserver.TransferShardLeaderRequest
	22, // 8: bedrock.dataserver.DataService.ShardRead:input_type -> bedrock.dataserver.ShardReadRequest
	24, // 9: bedrock.dataserver.DataService.ShardWrite:input_type -> bedrock.dataserver.ShardWriteRequest
	26, // 10: bedrock.dataserver.DataService.ShardAppendLog:input_type -> bedrock.dataserver.ShardAppendLogRequest
	28, // 11: bedrock.dataserver.DataService.ShardInstallSnapshot:input_type -> bedrock.dataserver.ShardInstallSnapshotRequest
	5,  // 12: bedrock.dataserver.DataService.CreateShard:output_type -> bedrock.dataserver.CreateShardResponse
	40, // 13: bedrock.dataserver.DataService.DeleteShard:output_type -> google.protobuf.Empty
	17, // 14: bedrock.dataserver.DataService.TransferShardLeader:output_type -> bedrock.dataserver.TransferShardLeaderResponse
	23, // 15: bedrock.dataserver.DataService.ShardRead:output_type -> bedrock.dataserver.ShardReadResponse
	25, // 16: bedrock.dataserver.DataService.ShardWrite:output_type -> bedrock.dataserver.ShardWriteResponse
	27, // 17: bedrock.dataserver.DataService.ShardAppendLog:output_type -> bedrock.dataserver.ShardAppendLogResponse
	29, // 18: bedrock.dataserver.DataService.ShardInstallSnapshot:output_type -> bedrock.dataserver.ShardInstallSnapshotResponse
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_dataserver_proto_init() }
func file_dataserver_proto_init() {
	if File_dataserver_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dataserver_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SplitShardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataserver_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SplitShardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataserver_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MergeShardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataserver_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MergeShardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataserver_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateShardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataserver_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateShardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataserver_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteShardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataserver_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteShardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataserver_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullShardDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataserver_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullShardDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataserver_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransferShardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataserver_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransferShardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataserver_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddShardReplicaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataserver_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddShardReplicaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataserver_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteShardReplicaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataserver_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteShardReplicaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataserver_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransferShardLeaderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataserver_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransferShardLeaderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataserver_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LockShardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataserver_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LockShardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataserver_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnlockShardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataserver_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnlockShardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataserver_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShardReadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataserver_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShardReadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataserver_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShardWriteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataserver_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShardWriteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataserver_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShardAppendLogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataserver_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShardAppendLogResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataserver_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShardInstallSnapshotRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataserver_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShardInstallSnapshotResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataserver_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShardWriteReplicaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataserver_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShardWriteReplicaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataserver_proto_msgTypes[32].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShardRepairRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataserver_proto_msgTypes[33].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShardRepairResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataserver_proto_msgTypes[34].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataServerJoinRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataserver_proto_msgTypes[35].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataServerJoinResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataserver_proto_msgTypes[36].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataServerLeaveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataserver_proto_msgTypes[37].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataServerLeaveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataserver_proto_msgTypes[38].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShardAppendLogRequest_Entry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dataserver_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   39,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dataserver_proto_goTypes,
		DependencyIndexes: file_dataserver_proto_depIdxs,
		MessageInfos:      file_dataserver_proto_msgTypes,
	}.Build()
	File_dataserver_proto = out.File
	file_dataserver_proto_rawDesc = nil
	file_dataserver_proto_goTypes = nil
	file_dataserver_proto_depIdxs = nil
}
