// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: metaserver.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Storage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DeletedTs *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=deleted_ts,json=deletedTs,proto3" json:"deleted_ts,omitempty"`
	CreateTs  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=create_ts,json=createTs,proto3" json:"create_ts,omitempty"`
	Owner     string                 `protobuf:"bytes,5,opt,name=owner,proto3" json:"owner,omitempty"`
}

func (x *Storage) Reset() {
	*x = Storage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metaserver_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Storage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Storage) ProtoMessage() {}

func (x *Storage) ProtoReflect() protoreflect.Message {
	mi := &file_metaserver_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Storage.ProtoReflect.Descriptor instead.
func (*Storage) Descriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{0}
}

func (x *Storage) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Storage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Storage) GetDeletedTs() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedTs
	}
	return nil
}

func (x *Storage) GetCreateTs() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTs
	}
	return nil
}

func (x *Storage) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

type Shard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	StorageId       uint64                 `protobuf:"varint,2,opt,name=storage_id,json=storageId,proto3" json:"storage_id,omitempty"`
	ReplicaUpdateTs *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=replica_update_ts,json=replicaUpdateTs,proto3" json:"replica_update_ts,omitempty"`
	Replicates      []string               `protobuf:"bytes,4,rep,name=replicates,proto3" json:"replicates,omitempty"`
	IsDeleted       bool                   `protobuf:"varint,5,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	DeletedTs       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=deleted_ts,json=deletedTs,proto3" json:"deleted_ts,omitempty"`
	CreateTs        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=create_ts,json=createTs,proto3" json:"create_ts,omitempty"`
	Leader          string                 `protobuf:"bytes,8,opt,name=leader,proto3" json:"leader,omitempty"`
	LeaderChangeTs  *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=leader_change_ts,json=leaderChangeTs,proto3" json:"leader_change_ts,omitempty"`
}

func (x *Shard) Reset() {
	*x = Shard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metaserver_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Shard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shard) ProtoMessage() {}

func (x *Shard) ProtoReflect() protoreflect.Message {
	mi := &file_metaserver_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shard.ProtoReflect.Descriptor instead.
func (*Shard) Descriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{1}
}

func (x *Shard) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Shard) GetStorageId() uint64 {
	if x != nil {
		return x.StorageId
	}
	return 0
}

func (x *Shard) GetReplicaUpdateTs() *timestamppb.Timestamp {
	if x != nil {
		return x.ReplicaUpdateTs
	}
	return nil
}

func (x *Shard) GetReplicates() []string {
	if x != nil {
		return x.Replicates
	}
	return nil
}

func (x *Shard) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

func (x *Shard) GetDeletedTs() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedTs
	}
	return nil
}

func (x *Shard) GetCreateTs() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTs
	}
	return nil
}

func (x *Shard) GetLeader() string {
	if x != nil {
		return x.Leader
	}
	return ""
}

func (x *Shard) GetLeaderChangeTs() *timestamppb.Timestamp {
	if x != nil {
		return x.LeaderChangeTs
	}
	return nil
}

type DataServer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip              uint32                 `protobuf:"varint,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port            uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Capacity        uint64                 `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Free            uint64                 `protobuf:"varint,4,opt,name=free,proto3" json:"free,omitempty"`
	LastHeartbeatTs *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_heartbeat_ts,json=lastHeartbeatTs,proto3" json:"last_heartbeat_ts,omitempty"`
	Status          string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Idc             string                 `protobuf:"bytes,7,opt,name=idc,proto3" json:"idc,omitempty"`
}

func (x *DataServer) Reset() {
	*x = DataServer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metaserver_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataServer) ProtoMessage() {}

func (x *DataServer) ProtoReflect() protoreflect.Message {
	mi := &file_metaserver_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataServer.ProtoReflect.Descriptor instead.
func (*DataServer) Descriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{2}
}

func (x *DataServer) GetIp() uint32 {
	if x != nil {
		return x.Ip
	}
	return 0
}

func (x *DataServer) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *DataServer) GetCapacity() uint64 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *DataServer) GetFree() uint64 {
	if x != nil {
		return x.Free
	}
	return 0
}

func (x *DataServer) GetLastHeartbeatTs() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHeartbeatTs
	}
	return nil
}

func (x *DataServer) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DataServer) GetIdc() string {
	if x != nil {
		return x.Idc
	}
	return ""
}

type Replicate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addrs []string `protobuf:"bytes,1,rep,name=addrs,proto3" json:"addrs,omitempty"`
}

func (x *Replicate) Reset() {
	*x = Replicate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metaserver_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Replicate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Replicate) ProtoMessage() {}

func (x *Replicate) ProtoReflect() protoreflect.Message {
	mi := &file_metaserver_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Replicate.ProtoReflect.Descriptor instead.
func (*Replicate) Descriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{3}
}

func (x *Replicate) GetAddrs() []string {
	if x != nil {
		return x.Addrs
	}
	return nil
}

type HeartBeatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
}

func (x *HeartBeatRequest) Reset() {
	*x = HeartBeatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metaserver_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartBeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartBeatRequest) ProtoMessage() {}

func (x *HeartBeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metaserver_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartBeatRequest.ProtoReflect.Descriptor instead.
func (*HeartBeatRequest) Descriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{4}
}

func (x *HeartBeatRequest) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type HeartBeatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HeartBeatResponse) Reset() {
	*x = HeartBeatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metaserver_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartBeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartBeatResponse) ProtoMessage() {}

func (x *HeartBeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metaserver_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartBeatResponse.ProtoReflect.Descriptor instead.
func (*HeartBeatResponse) Descriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{5}
}

type CreateStorageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CreateStorageRequest) Reset() {
	*x = CreateStorageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metaserver_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateStorageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStorageRequest) ProtoMessage() {}

func (x *CreateStorageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metaserver_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStorageRequest.ProtoReflect.Descriptor instead.
func (*CreateStorageRequest) Descriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{6}
}

func (x *CreateStorageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateStorageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateStorageResponse) Reset() {
	*x = CreateStorageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metaserver_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateStorageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStorageResponse) ProtoMessage() {}

func (x *CreateStorageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metaserver_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStorageResponse.ProtoReflect.Descriptor instead.
func (*CreateStorageResponse) Descriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{7}
}

func (x *CreateStorageResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteStorageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RealDelete   bool   `protobuf:"varint,2,opt,name=real_delete,json=realDelete,proto3" json:"real_delete,omitempty"`
	RecycleAfter uint64 `protobuf:"varint,3,opt,name=recycle_after,json=recycleAfter,proto3" json:"recycle_after,omitempty"` // in minutes
}

func (x *DeleteStorageRequest) Reset() {
	*x = DeleteStorageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metaserver_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteStorageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStorageRequest) ProtoMessage() {}

func (x *DeleteStorageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metaserver_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStorageRequest.ProtoReflect.Descriptor instead.
func (*DeleteStorageRequest) Descriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteStorageRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteStorageRequest) GetRealDelete() bool {
	if x != nil {
		return x.RealDelete
	}
	return false
}

func (x *DeleteStorageRequest) GetRecycleAfter() uint64 {
	if x != nil {
		return x.RecycleAfter
	}
	return 0
}

type DeleteStorageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteStorageResponse) Reset() {
	*x = DeleteStorageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metaserver_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteStorageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStorageResponse) ProtoMessage() {}

func (x *DeleteStorageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metaserver_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStorageResponse.ProtoReflect.Descriptor instead.
func (*DeleteStorageResponse) Descriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{9}
}

type UndeleteStorageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UndeleteStorageRequest) Reset() {
	*x = UndeleteStorageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metaserver_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UndeleteStorageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UndeleteStorageRequest) ProtoMessage() {}

func (x *UndeleteStorageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metaserver_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UndeleteStorageRequest.ProtoReflect.Descriptor instead.
func (*UndeleteStorageRequest) Descriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{10}
}

func (x *UndeleteStorageRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UndeleteStorageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UndeleteStorageResponse) Reset() {
	*x = UndeleteStorageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metaserver_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UndeleteStorageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UndeleteStorageResponse) ProtoMessage() {}

func (x *UndeleteStorageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metaserver_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UndeleteStorageResponse.ProtoReflect.Descriptor instead.
func (*UndeleteStorageResponse) Descriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{11}
}

type RenameStorageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NewName string `protobuf:"bytes,2,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
}

func (x *RenameStorageRequest) Reset() {
	*x = RenameStorageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metaserver_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RenameStorageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameStorageRequest) ProtoMessage() {}

func (x *RenameStorageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metaserver_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameStorageRequest.ProtoReflect.Descriptor instead.
func (*RenameStorageRequest) Descriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{12}
}

func (x *RenameStorageRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RenameStorageRequest) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

type RenameStorageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RenameStorageResponse) Reset() {
	*x = RenameStorageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metaserver_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RenameStorageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameStorageResponse) ProtoMessage() {}

func (x *RenameStorageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metaserver_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameStorageResponse.ProtoReflect.Descriptor instead.
func (*RenameStorageResponse) Descriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{13}
}

type ResizeStorageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NewSize       uint64 `protobuf:"varint,2,opt,name=new_size,json=newSize,proto3" json:"new_size,omitempty"`
	NewShardCount uint64 `protobuf:"varint,3,opt,name=new_shard_count,json=newShardCount,proto3" json:"new_shard_count,omitempty"`
}

func (x *ResizeStorageRequest) Reset() {
	*x = ResizeStorageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metaserver_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResizeStorageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizeStorageRequest) ProtoMessage() {}

func (x *ResizeStorageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metaserver_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizeStorageRequest.ProtoReflect.Descriptor instead.
func (*ResizeStorageRequest) Descriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{14}
}

func (x *ResizeStorageRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ResizeStorageRequest) GetNewSize() uint64 {
	if x != nil {
		return x.NewSize
	}
	return 0
}

func (x *ResizeStorageRequest) GetNewShardCount() uint64 {
	if x != nil {
		return x.NewShardCount
	}
	return 0
}

type ResizeStorageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ResizeStorageResponse) Reset() {
	*x = ResizeStorageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metaserver_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResizeStorageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizeStorageResponse) ProtoMessage() {}

func (x *ResizeStorageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metaserver_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizeStorageResponse.ProtoReflect.Descriptor instead.
func (*ResizeStorageResponse) Descriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{15}
}

type GetStoragesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids   []uint64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	Names []string `protobuf:"bytes,2,rep,name=names,proto3" json:"names,omitempty"`
}

func (x *GetStoragesRequest) Reset() {
	*x = GetStoragesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metaserver_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStoragesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoragesRequest) ProtoMessage() {}

func (x *GetStoragesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metaserver_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoragesRequest.ProtoReflect.Descriptor instead.
func (*GetStoragesRequest) Descriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{16}
}

func (x *GetStoragesRequest) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *GetStoragesRequest) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type GetStoragesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Storages []*Storage `protobuf:"bytes,1,rep,name=storages,proto3" json:"storages,omitempty"`
}

func (x *GetStoragesResponse) Reset() {
	*x = GetStoragesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metaserver_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStoragesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoragesResponse) ProtoMessage() {}

func (x *GetStoragesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metaserver_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoragesResponse.ProtoReflect.Descriptor instead.
func (*GetStoragesResponse) Descriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{17}
}

func (x *GetStoragesResponse) GetStorages() []*Storage {
	if x != nil {
		return x.Storages
	}
	return nil
}

type ShardRange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartShardId uint64 `protobuf:"varint,1,opt,name=start_shard_id,json=startShardId,proto3" json:"start_shard_id,omitempty"`
	Offset       uint64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *ShardRange) Reset() {
	*x = ShardRange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metaserver_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShardRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardRange) ProtoMessage() {}

func (x *ShardRange) ProtoReflect() protoreflect.Message {
	mi := &file_metaserver_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardRange.ProtoReflect.Descriptor instead.
func (*ShardRange) Descriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{18}
}

func (x *ShardRange) GetStartShardId() uint64 {
	if x != nil {
		return x.StartShardId
	}
	return 0
}

func (x *ShardRange) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type RouteRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShardId uint64   `protobuf:"varint,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Addrs   []string `protobuf:"bytes,2,rep,name=addrs,proto3" json:"addrs,omitempty"`
}

func (x *RouteRecord) Reset() {
	*x = RouteRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metaserver_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RouteRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteRecord) ProtoMessage() {}

func (x *RouteRecord) ProtoReflect() protoreflect.Message {
	mi := &file_metaserver_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteRecord.ProtoReflect.Descriptor instead.
func (*RouteRecord) Descriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{19}
}

func (x *RouteRecord) GetShardId() uint64 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *RouteRecord) GetAddrs() []string {
	if x != nil {
		return x.Addrs
	}
	return nil
}

type ShardList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShardIds []uint64 `protobuf:"varint,1,rep,packed,name=shard_ids,json=shardIds,proto3" json:"shard_ids,omitempty"`
}

func (x *ShardList) Reset() {
	*x = ShardList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metaserver_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShardList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardList) ProtoMessage() {}

func (x *ShardList) ProtoReflect() protoreflect.Message {
	mi := &file_metaserver_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardList.ProtoReflect.Descriptor instead.
func (*ShardList) Descriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{20}
}

func (x *ShardList) GetShardIds() []uint64 {
	if x != nil {
		return x.ShardIds
	}
	return nil
}

type GetShardRoutesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Shards:
	//	*GetShardRoutesRequest_ShardsList
	//	*GetShardRoutesRequest_ShardRange
	Shards    isGetShardRoutesRequest_Shards `protobuf_oneof:"shards"`
	Timestamp *timestamppb.Timestamp         `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *GetShardRoutesRequest) Reset() {
	*x = GetShardRoutesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metaserver_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShardRoutesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShardRoutesRequest) ProtoMessage() {}

func (x *GetShardRoutesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metaserver_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShardRoutesRequest.ProtoReflect.Descriptor instead.
func (*GetShardRoutesRequest) Descriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{21}
}

func (m *GetShardRoutesRequest) GetShards() isGetShardRoutesRequest_Shards {
	if m != nil {
		return m.Shards
	}
	return nil
}

func (x *GetShardRoutesRequest) GetShardsList() *ShardList {
	if x, ok := x.GetShards().(*GetShardRoutesRequest_ShardsList); ok {
		return x.ShardsList
	}
	return nil
}

func (x *GetShardRoutesRequest) GetShardRange() *ShardRange {
	if x, ok := x.GetShards().(*GetShardRoutesRequest_ShardRange); ok {
		return x.ShardRange
	}
	return nil
}

func (x *GetShardRoutesRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type isGetShardRoutesRequest_Shards interface {
	isGetShardRoutesRequest_Shards()
}

type GetShardRoutesRequest_ShardsList struct {
	ShardsList *ShardList `protobuf:"bytes,1,opt,name=shards_list,json=shardsList,proto3,oneof"`
}

type GetShardRoutesRequest_ShardRange struct {
	ShardRange *ShardRange `protobuf:"bytes,2,opt,name=shard_range,json=shardRange,proto3,oneof"`
}

func (*GetShardRoutesRequest_ShardsList) isGetShardRoutesRequest_Shards() {}

func (*GetShardRoutesRequest_ShardRange) isGetShardRoutesRequest_Shards() {}

type GetShardRoutesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Routes []*RouteRecord `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
}

func (x *GetShardRoutesResponse) Reset() {
	*x = GetShardRoutesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metaserver_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShardRoutesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShardRoutesResponse) ProtoMessage() {}

func (x *GetShardRoutesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metaserver_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShardRoutesResponse.ProtoReflect.Descriptor instead.
func (*GetShardRoutesResponse) Descriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{22}
}

func (x *GetShardRoutesResponse) GetRoutes() []*RouteRecord {
	if x != nil {
		return x.Routes
	}
	return nil
}

type GetShardRoutesByStorageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StorageId uint64                 `protobuf:"varint,1,opt,name=storage_id,json=storageId,proto3" json:"storage_id,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *GetShardRoutesByStorageRequest) Reset() {
	*x = GetShardRoutesByStorageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metaserver_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShardRoutesByStorageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShardRoutesByStorageRequest) ProtoMessage() {}

func (x *GetShardRoutesByStorageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metaserver_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShardRoutesByStorageRequest.ProtoReflect.Descriptor instead.
func (*GetShardRoutesByStorageRequest) Descriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{23}
}

func (x *GetShardRoutesByStorageRequest) GetStorageId() uint64 {
	if x != nil {
		return x.StorageId
	}
	return 0
}

func (x *GetShardRoutesByStorageRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type GetShardRoutesByStorageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Routes    []*RouteRecord         `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	IsFull    bool                   `protobuf:"varint,3,opt,name=is_full,json=isFull,proto3" json:"is_full,omitempty"`
}

func (x *GetShardRoutesByStorageResponse) Reset() {
	*x = GetShardRoutesByStorageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metaserver_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShardRoutesByStorageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShardRoutesByStorageResponse) ProtoMessage() {}

func (x *GetShardRoutesByStorageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metaserver_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShardRoutesByStorageResponse.ProtoReflect.Descriptor instead.
func (*GetShardRoutesByStorageResponse) Descriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{24}
}

func (x *GetShardRoutesByStorageResponse) GetRoutes() []*RouteRecord {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *GetShardRoutesByStorageResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *GetShardRoutesByStorageResponse) GetIsFull() bool {
	if x != nil {
		return x.IsFull
	}
	return false
}

type AddDataServerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
}

func (x *AddDataServerRequest) Reset() {
	*x = AddDataServerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metaserver_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddDataServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDataServerRequest) ProtoMessage() {}

func (x *AddDataServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metaserver_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDataServerRequest.ProtoReflect.Descriptor instead.
func (*AddDataServerRequest) Descriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{25}
}

func (x *AddDataServerRequest) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type AddDataServerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddDataServerResponse) Reset() {
	*x = AddDataServerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metaserver_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddDataServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDataServerResponse) ProtoMessage() {}

func (x *AddDataServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metaserver_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDataServerResponse.ProtoReflect.Descriptor instead.
func (*AddDataServerResponse) Descriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{26}
}

type RemoveDataServerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
}

func (x *RemoveDataServerRequest) Reset() {
	*x = RemoveDataServerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metaserver_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveDataServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveDataServerRequest) ProtoMessage() {}

func (x *RemoveDataServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metaserver_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveDataServerRequest.ProtoReflect.Descriptor instead.
func (*RemoveDataServerRequest) Descriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{27}
}

func (x *RemoveDataServerRequest) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type RemoveDataServerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RemoveDataServerResponse) Reset() {
	*x = RemoveDataServerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metaserver_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveDataServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveDataServerResponse) ProtoMessage() {}

func (x *RemoveDataServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metaserver_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveDataServerResponse.ProtoReflect.Descriptor instead.
func (*RemoveDataServerResponse) Descriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{28}
}

type ListDataServerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListDataServerRequest) Reset() {
	*x = ListDataServerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metaserver_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDataServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDataServerRequest) ProtoMessage() {}

func (x *ListDataServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metaserver_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDataServerRequest.ProtoReflect.Descriptor instead.
func (*ListDataServerRequest) Descriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{29}
}

type ListDataServerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataServers []*DataServer `protobuf:"bytes,1,rep,name=data_servers,json=dataServers,proto3" json:"data_servers,omitempty"`
}

func (x *ListDataServerResponse) Reset() {
	*x = ListDataServerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metaserver_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDataServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDataServerResponse) ProtoMessage() {}

func (x *ListDataServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metaserver_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDataServerResponse.ProtoReflect.Descriptor instead.
func (*ListDataServerResponse) Descriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{30}
}

func (x *ListDataServerResponse) GetDataServers() []*DataServer {
	if x != nil {
		return x.DataServers
	}
	return nil
}

type UpdateDataServerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateDataServerRequest) Reset() {
	*x = UpdateDataServerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metaserver_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDataServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDataServerRequest) ProtoMessage() {}

func (x *UpdateDataServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metaserver_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDataServerRequest.ProtoReflect.Descriptor instead.
func (*UpdateDataServerRequest) Descriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{31}
}

type UpdateDataServerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateDataServerResponse) Reset() {
	*x = UpdateDataServerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metaserver_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDataServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDataServerResponse) ProtoMessage() {}

func (x *UpdateDataServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metaserver_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDataServerResponse.ProtoReflect.Descriptor instead.
func (*UpdateDataServerResponse) Descriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{32}
}

type ShardInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ShardInfoRequest) Reset() {
	*x = ShardInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metaserver_proto_msgTypes[33]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShardInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardInfoRequest) ProtoMessage() {}

func (x *ShardInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metaserver_proto_msgTypes[33]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardInfoRequest.ProtoReflect.Descriptor instead.
func (*ShardInfoRequest) Descriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{33}
}

func (x *ShardInfoRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ShardInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Shard *Shard `protobuf:"bytes,1,opt,name=shard,proto3" json:"shard,omitempty"`
}

func (x *ShardInfoResponse) Reset() {
	*x = ShardInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metaserver_proto_msgTypes[34]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShardInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardInfoResponse) ProtoMessage() {}

func (x *ShardInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metaserver_proto_msgTypes[34]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardInfoResponse.ProtoReflect.Descriptor instead.
func (*ShardInfoResponse) Descriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{34}
}

func (x *ShardInfoResponse) GetShard() *Shard {
	if x != nil {
		return x.Shard
	}
	return nil
}

var File_metaserver_proto protoreflect.FileDescriptor

var file_metaserver_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6d, 0x65, 0x74, 0x61, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x12, 0x62, 0x65, 0x64, 0x72, 0x6f, 0x63, 0x6b, 0x2e, 0x6d, 0x65, 0x74, 0x61,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb7, 0x01, 0x0a, 0x07, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f,
	0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x54, 0x73, 0x12,
	0x37, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x08,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65,
	0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x22, 0x8f,
	0x03, 0x0a, 0x05, 0x53, 0x68, 0x61, 0x72, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x73, 0x74,
	0x6f, 0x72, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x46, 0x0a, 0x11, 0x72, 0x65, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0f,
	0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x73, 0x12,
	0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x73, 0x12,
	0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x12, 0x39,
	0x0a, 0x0a, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x74, 0x73, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09,
	0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x54, 0x73, 0x12, 0x37, 0x0a, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x5f, 0x74, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x44, 0x0a, 0x10, 0x6c, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x74, 0x73, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x0e, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x73,
	0x22, 0xd2, 0x01, 0x0a, 0x0a, 0x44, 0x61, 0x74, 0x61, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x70, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70,
	0x6f, 0x72, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x12,
	0x12, 0x0a, 0x04, 0x66, 0x72, 0x65, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x66,
	0x72, 0x65, 0x65, 0x12, 0x46, 0x0a, 0x11, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x68, 0x65, 0x61, 0x72,
	0x74, 0x62, 0x65, 0x61, 0x74, 0x5f, 0x74, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0f, 0x6c, 0x61, 0x73, 0x74,
	0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x54, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x63, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x69, 0x64, 0x63, 0x22, 0x21, 0x0a, 0x09, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x64, 0x64, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x05, 0x61, 0x64, 0x64, 0x72, 0x73, 0x22, 0x26, 0x0a, 0x10, 0x48, 0x65, 0x61, 0x72,
	0x74, 0x42, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72,
	0x22, 0x13, 0x0a, 0x11, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2a, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x27, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x6c, 0x0a, 0x14, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x61, 0x6c, 0x5f, 0x64, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x72, 0x65, 0x61, 0x6c, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x5f, 0x61,
	0x66, 0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x72, 0x65, 0x63, 0x79,
	0x63, 0x6c, 0x65, 0x41, 0x66, 0x74, 0x65, 0x72, 0x22, 0x17, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x28, 0x0a, 0x16, 0x55, 0x6e, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x19, 0x0a, 0x17, 0x55,
	0x6e, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x41, 0x0a, 0x14, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65,
	0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x19,
	0x0a, 0x08, 0x6e, 0x65, 0x77, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6e, 0x65, 0x77, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x17, 0x0a, 0x15, 0x52, 0x65, 0x6e,
	0x61, 0x6d, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x69, 0x0a, 0x14, 0x52, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x53, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6e, 0x65,
	0x77, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x6e, 0x65,
	0x77, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x26, 0x0a, 0x0f, 0x6e, 0x65, 0x77, 0x5f, 0x73, 0x68, 0x61,
	0x72, 0x64, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d,
	0x6e, 0x65, 0x77, 0x53, 0x68, 0x61, 0x72, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x17, 0x0a,
	0x15, 0x52, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x3c, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x53, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x03, 0x69, 0x64, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x6e,
	0x61, 0x6d, 0x65, 0x73, 0x22, 0x4e, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x08, 0x73,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x62, 0x65, 0x64, 0x72, 0x6f, 0x63, 0x6b, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x08, 0x73, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x73, 0x22, 0x4a, 0x0a, 0x0a, 0x53, 0x68, 0x61, 0x72, 0x64, 0x52, 0x61, 0x6e,
	0x67, 0x65, 0x12, 0x24, 0x0a, 0x0e, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x73, 0x68, 0x61, 0x72,
	0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x53, 0x68, 0x61, 0x72, 0x64, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73,
	0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74,
	0x22, 0x3e, 0x0a, 0x0b, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12,
	0x19, 0x0a, 0x08, 0x73, 0x68, 0x61, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x07, 0x73, 0x68, 0x61, 0x72, 0x64, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x64,
	0x64, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x61, 0x64, 0x64, 0x72, 0x73,
	0x22, 0x28, 0x0a, 0x09, 0x53, 0x68, 0x61, 0x72, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1b, 0x0a,
	0x09, 0x73, 0x68, 0x61, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04,
	0x52, 0x08, 0x73, 0x68, 0x61, 0x72, 0x64, 0x49, 0x64, 0x73, 0x22, 0xe0, 0x01, 0x0a, 0x15, 0x47,
	0x65, 0x74, 0x53, 0x68, 0x61, 0x72, 0x64, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x40, 0x0a, 0x0b, 0x73, 0x68, 0x61, 0x72, 0x64, 0x73, 0x5f, 0x6c,
	0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x62, 0x65, 0x64, 0x72,
	0x6f, 0x63, 0x6b, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x53,
	0x68, 0x61, 0x72, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0a, 0x73, 0x68, 0x61, 0x72,
	0x64, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x41, 0x0a, 0x0b, 0x73, 0x68, 0x61, 0x72, 0x64, 0x5f,
	0x72, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x62, 0x65,
	0x64, 0x72, 0x6f, 0x63, 0x6b, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x53, 0x68, 0x61, 0x72, 0x64, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x48, 0x00, 0x52, 0x0a, 0x73,
	0x68, 0x61, 0x72, 0x64, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x42, 0x08, 0x0a, 0x06, 0x73, 0x68, 0x61, 0x72, 0x64, 0x73, 0x22, 0x51, 0x0a,
	0x16, 0x47, 0x65, 0x74, 0x53, 0x68, 0x61, 0x72, 0x64, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x06, 0x72, 0x6f, 0x75, 0x74, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x62, 0x65, 0x64, 0x72, 0x6f, 0x63,
	0x6b, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x6f, 0x75,
	0x74, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x06, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x73,
	0x22, 0x79, 0x0a, 0x1e, 0x47, 0x65, 0x74, 0x53, 0x68, 0x61, 0x72, 0x64, 0x52, 0x6f, 0x75, 0x74,
	0x65, 0x73, 0x42, 0x79, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x49,
	0x64, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0xad, 0x01, 0x0a, 0x1f,
	0x47, 0x65, 0x74, 0x53, 0x68, 0x61, 0x72, 0x64, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x42, 0x79,
	0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x37, 0x0a, 0x06, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1f, 0x2e, 0x62, 0x65, 0x64, 0x72, 0x6f, 0x63, 0x6b, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x52, 0x06, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x66, 0x75, 0x6c, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x46, 0x75, 0x6c, 0x6c, 0x22, 0x2a, 0x0a, 0x14, 0x41,
	0x64, 0x64, 0x44, 0x61, 0x74, 0x61, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x22, 0x17, 0x0a, 0x15, 0x41, 0x64, 0x64, 0x44, 0x61,
	0x74, 0x61, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x2d, 0x0a, 0x17, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x44, 0x61, 0x74, 0x61, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x61,
	0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x22,
	0x1a, 0x0a, 0x18, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x44, 0x61, 0x74, 0x61, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x17, 0x0a, 0x15, 0x4c,
	0x69, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x5b, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41,
	0x0a, 0x0c, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x62, 0x65, 0x64, 0x72, 0x6f, 0x63, 0x6b, 0x2e, 0x6d,
	0x65, 0x74, 0x61, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x52, 0x0b, 0x64, 0x61, 0x74, 0x61, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x73, 0x22, 0x19, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1a, 0x0a, 0x18,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x22, 0x0a, 0x10, 0x53, 0x68, 0x61, 0x72,
	0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x44, 0x0a, 0x11,
	0x53, 0x68, 0x61, 0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2f, 0x0a, 0x05, 0x73, 0x68, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x62, 0x65, 0x64, 0x72, 0x6f, 0x63, 0x6b, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x64, 0x52, 0x05, 0x73, 0x68, 0x61,
	0x72, 0x64, 0x32, 0xac, 0x0a, 0x0a, 0x0b, 0x4d, 0x65, 0x74, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x49, 0x0a, 0x09, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x12,
	0x24, 0x2e, 0x62, 0x65, 0x64, 0x72, 0x6f, 0x63, 0x6b, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x67, 0x0a,
	0x0e, 0x47, 0x65, 0x74, 0x53, 0x68, 0x61, 0x72, 0x64, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x12,
	0x29, 0x2e, 0x62, 0x65, 0x64, 0x72, 0x6f, 0x63, 0x6b, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x68, 0x61, 0x72, 0x64, 0x52, 0x6f, 0x75,
	0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x62, 0x65, 0x64,
	0x72, 0x6f, 0x63, 0x6b, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x47, 0x65, 0x74, 0x53, 0x68, 0x61, 0x72, 0x64, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x64, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x12, 0x28, 0x2e, 0x62, 0x65, 0x64, 0x72, 0x6f, 0x63,
	0x6b, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x29, 0x2e, 0x62, 0x65, 0x64, 0x72, 0x6f, 0x63, 0x6b, 0x2e, 0x6d, 0x65, 0x74, 0x61,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x64, 0x0a, 0x0d,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x12, 0x28, 0x2e,
	0x62, 0x65, 0x64, 0x72, 0x6f, 0x63, 0x6b, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x62, 0x65, 0x64, 0x72, 0x6f, 0x63,
	0x6b, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x6a, 0x0a, 0x0f, 0x55, 0x6e, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x74,
	0x6f, 0x72, 0x61, 0x67, 0x65, 0x12, 0x2a, 0x2e, 0x62, 0x65, 0x64, 0x72, 0x6f, 0x63, 0x6b, 0x2e,
	0x6d, 0x65, 0x74, 0x61, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x55, 0x6e, 0x64, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x2b, 0x2e, 0x62, 0x65, 0x64, 0x72, 0x6f, 0x63, 0x6b, 0x2e, 0x6d, 0x65, 0x74, 0x61,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x55, 0x6e, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x64,
	0x0a, 0x0d, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x12,
	0x28, 0x2e, 0x62, 0x65, 0x64, 0x72, 0x6f, 0x63, 0x6b, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x62, 0x65, 0x64, 0x72,
	0x6f, 0x63, 0x6b, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52,
	0x65, 0x6e, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x64, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x53, 0x74,
	0x6f, 0x72, 0x61, 0x67, 0x65, 0x12, 0x28, 0x2e, 0x62, 0x65, 0x64, 0x72, 0x6f, 0x63, 0x6b, 0x2e,
	0x6d, 0x65, 0x74, 0x61, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x69, 0x7a,
	0x65, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x29, 0x2e, 0x62, 0x65, 0x64, 0x72, 0x6f, 0x63, 0x6b, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5e, 0x0a, 0x0b, 0x47, 0x65,
	0x74, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x73, 0x12, 0x26, 0x2e, 0x62, 0x65, 0x64, 0x72,
	0x6f, 0x63, 0x6b, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x47,
	0x65, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x27, 0x2e, 0x62, 0x65, 0x64, 0x72, 0x6f, 0x63, 0x6b, 0x2e, 0x6d, 0x65, 0x74, 0x61,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x64, 0x0a, 0x0d, 0x41, 0x64,
	0x64, 0x44, 0x61, 0x74, 0x61, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x28, 0x2e, 0x62, 0x65,
	0x64, 0x72, 0x6f, 0x63, 0x6b, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x41, 0x64, 0x64, 0x44, 0x61, 0x74, 0x61, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x62, 0x65, 0x64, 0x72, 0x6f, 0x63, 0x6b, 0x2e,
	0x6d, 0x65, 0x74, 0x61, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x41, 0x64, 0x64, 0x44, 0x61,
	0x74, 0x61, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x6d, 0x0a, 0x10, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x44, 0x61, 0x74, 0x61, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x12, 0x2b, 0x2e, 0x62, 0x65, 0x64, 0x72, 0x6f, 0x63, 0x6b, 0x2e, 0x6d,
	0x65, 0x74, 0x61, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x2c, 0x2e, 0x62, 0x65, 0x64, 0x72, 0x6f, 0x63, 0x6b, 0x2e, 0x6d, 0x65, 0x74, 0x61,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x44, 0x61, 0x74,
	0x61, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x67, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x12, 0x29, 0x2e, 0x62, 0x65, 0x64, 0x72, 0x6f, 0x63, 0x6b, 0x2e, 0x6d, 0x65, 0x74, 0x61,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x62,
	0x65, 0x64, 0x72, 0x6f, 0x63, 0x6b, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6d, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x2b, 0x2e, 0x62,
	0x65, 0x64, 0x72, 0x6f, 0x63, 0x6b, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x62, 0x65, 0x64, 0x72,
	0x6f, 0x63, 0x6b, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x58, 0x0a, 0x09, 0x53, 0x68, 0x61, 0x72, 0x64,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x24, 0x2e, 0x62, 0x65, 0x64, 0x72, 0x6f, 0x63, 0x6b, 0x2e, 0x6d,
	0x65, 0x74, 0x61, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x64, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x62, 0x65, 0x64,
	0x72, 0x6f, 0x63, 0x6b, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x53, 0x68, 0x61, 0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x2c, 0x5a, 0x27, 0x73, 0x72, 0x2e, 0x68, 0x74, 0x2f, 0x6d, 0x6f, 0x79, 0x61, 0x6e,
	0x68, 0x61, 0x6f, 0x2f, 0x62, 0x65, 0x64, 0x72, 0x6f, 0x63, 0x6b, 0x2d, 0x6d, 0x65, 0x74, 0x61,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x80, 0x01, 0x01, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_metaserver_proto_rawDescOnce sync.Once
	file_metaserver_proto_rawDescData = file_metaserver_proto_rawDesc
)

func file_metaserver_proto_rawDescGZIP() []byte {
	file_metaserver_proto_rawDescOnce.Do(func() {
		file_metaserver_proto_rawDescData = protoimpl.X.CompressGZIP(file_metaserver_proto_rawDescData)
	})
	return file_metaserver_proto_rawDescData
}

var file_metaserver_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_metaserver_proto_goTypes = []interface{}{
	(*Storage)(nil),                         // 0: bedrock.metaserver.Storage
	(*Shard)(nil),                           // 1: bedrock.metaserver.Shard
	(*DataServer)(nil),                      // 2: bedrock.metaserver.DataServer
	(*Replicate)(nil),                       // 3: bedrock.metaserver.Replicate
	(*HeartBeatRequest)(nil),                // 4: bedrock.metaserver.HeartBeatRequest
	(*HeartBeatResponse)(nil),               // 5: bedrock.metaserver.HeartBeatResponse
	(*CreateStorageRequest)(nil),            // 6: bedrock.metaserver.CreateStorageRequest
	(*CreateStorageResponse)(nil),           // 7: bedrock.metaserver.CreateStorageResponse
	(*DeleteStorageRequest)(nil),            // 8: bedrock.metaserver.DeleteStorageRequest
	(*DeleteStorageResponse)(nil),           // 9: bedrock.metaserver.DeleteStorageResponse
	(*UndeleteStorageRequest)(nil),          // 10: bedrock.metaserver.UndeleteStorageRequest
	(*UndeleteStorageResponse)(nil),         // 11: bedrock.metaserver.UndeleteStorageResponse
	(*RenameStorageRequest)(nil),            // 12: bedrock.metaserver.RenameStorageRequest
	(*RenameStorageResponse)(nil),           // 13: bedrock.metaserver.RenameStorageResponse
	(*ResizeStorageRequest)(nil),            // 14: bedrock.metaserver.ResizeStorageRequest
	(*ResizeStorageResponse)(nil),           // 15: bedrock.metaserver.ResizeStorageResponse
	(*GetStoragesRequest)(nil),              // 16: bedrock.metaserver.GetStoragesRequest
	(*GetStoragesResponse)(nil),             // 17: bedrock.metaserver.GetStoragesResponse
	(*ShardRange)(nil),                      // 18: bedrock.metaserver.ShardRange
	(*RouteRecord)(nil),                     // 19: bedrock.metaserver.RouteRecord
	(*ShardList)(nil),                       // 20: bedrock.metaserver.ShardList
	(*GetShardRoutesRequest)(nil),           // 21: bedrock.metaserver.GetShardRoutesRequest
	(*GetShardRoutesResponse)(nil),          // 22: bedrock.metaserver.GetShardRoutesResponse
	(*GetShardRoutesByStorageRequest)(nil),  // 23: bedrock.metaserver.GetShardRoutesByStorageRequest
	(*GetShardRoutesByStorageResponse)(nil), // 24: bedrock.metaserver.GetShardRoutesByStorageResponse
	(*AddDataServerRequest)(nil),            // 25: bedrock.metaserver.AddDataServerRequest
	(*AddDataServerResponse)(nil),           // 26: bedrock.metaserver.AddDataServerResponse
	(*RemoveDataServerRequest)(nil),         // 27: bedrock.metaserver.RemoveDataServerRequest
	(*RemoveDataServerResponse)(nil),        // 28: bedrock.metaserver.RemoveDataServerResponse
	(*ListDataServerRequest)(nil),           // 29: bedrock.metaserver.ListDataServerRequest
	(*ListDataServerResponse)(nil),          // 30: bedrock.metaserver.ListDataServerResponse
	(*UpdateDataServerRequest)(nil),         // 31: bedrock.metaserver.UpdateDataServerRequest
	(*UpdateDataServerResponse)(nil),        // 32: bedrock.metaserver.UpdateDataServerResponse
	(*ShardInfoRequest)(nil),                // 33: bedrock.metaserver.ShardInfoRequest
	(*ShardInfoResponse)(nil),               // 34: bedrock.metaserver.ShardInfoResponse
	(*timestamppb.Timestamp)(nil),           // 35: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                   // 36: google.protobuf.Empty
}
var file_metaserver_proto_depIdxs = []int32{
	35, // 0: bedrock.metaserver.Storage.deleted_ts:type_name -> google.protobuf.Timestamp
	35, // 1: bedrock.metaserver.Storage.create_ts:type_name -> google.protobuf.Timestamp
	35, // 2: bedrock.metaserver.Shard.replica_update_ts:type_name -> google.protobuf.Timestamp
	35, // 3: bedrock.metaserver.Shard.deleted_ts:type_name -> google.protobuf.Timestamp
	35, // 4: bedrock.metaserver.Shard.create_ts:type_name -> google.protobuf.Timestamp
	35, // 5: bedrock.metaserver.Shard.leader_change_ts:type_name -> google.protobuf.Timestamp
	35, // 6: bedrock.metaserver.DataServer.last_heartbeat_ts:type_name -> google.protobuf.Timestamp
	0,  // 7: bedrock.metaserver.GetStoragesResponse.storages:type_name -> bedrock.metaserver.Storage
	20, // 8: bedrock.metaserver.GetShardRoutesRequest.shards_list:type_name -> bedrock.metaserver.ShardList
	18, // 9: bedrock.metaserver.GetShardRoutesRequest.shard_range:type_name -> bedrock.metaserver.ShardRange
	35, // 10: bedrock.metaserver.GetShardRoutesRequest.timestamp:type_name -> google.protobuf.Timestamp
	19, // 11: bedrock.metaserver.GetShardRoutesResponse.routes:type_name -> bedrock.metaserver.RouteRecord
	35, // 12: bedrock.metaserver.GetShardRoutesByStorageRequest.timestamp:type_name -> google.protobuf.Timestamp
	19, // 13: bedrock.metaserver.GetShardRoutesByStorageResponse.routes:type_name -> bedrock.metaserver.RouteRecord
	35, // 14: bedrock.metaserver.GetShardRoutesByStorageResponse.timestamp:type_name -> google.protobuf.Timestamp
	2,  // 15: bedrock.metaserver.ListDataServerResponse.data_servers:type_name -> bedrock.metaserver.DataServer
	1,  // 16: bedrock.metaserver.ShardInfoResponse.shard:type_name -> bedrock.metaserver.Shard
	4,  // 17: bedrock.metaserver.MetaService.HeartBeat:input_type -> bedrock.metaserver.HeartBeatRequest
	21, // 18: bedrock.metaserver.MetaService.GetShardRoutes:input_type -> bedrock.metaserver.GetShardRoutesRequest
	6,  // 19: bedrock.metaserver.MetaService.CreateStorage:input_type -> bedrock.metaserver.CreateStorageRequest
	8,  // 20: bedrock.metaserver.MetaService.DeleteStorage:input_type -> bedrock.metaserver.DeleteStorageRequest
	10, // 21: bedrock.metaserver.MetaService.UndeleteStorage:input_type -> bedrock.metaserver.UndeleteStorageRequest
	12, // 22: bedrock.metaserver.MetaService.RenameStorage:input_type -> bedrock.metaserver.RenameStorageRequest
	14, // 23: bedrock.metaserver.MetaService.ResizeStorage:input_type -> bedrock.metaserver.ResizeStorageRequest
	16, // 24: bedrock.metaserver.MetaService.GetStorages:input_type -> bedrock.metaserver.GetStoragesRequest
	25, // 25: bedrock.metaserver.MetaService.AddDataServer:input_type -> bedrock.metaserver.AddDataServerRequest
	27, // 26: bedrock.metaserver.MetaService.RemoveDataServer:input_type -> bedrock.metaserver.RemoveDataServerRequest
	29, // 27: bedrock.metaserver.MetaService.ListDataServer:input_type -> bedrock.metaserver.ListDataServerRequest
	31, // 28: bedrock.metaserver.MetaService.UpdateDataServer:input_type -> bedrock.metaserver.UpdateDataServerRequest
	33, // 29: bedrock.metaserver.MetaService.ShardInfo:input_type -> bedrock.metaserver.ShardInfoRequest
	36, // 30: bedrock.metaserver.MetaService.HeartBeat:output_type -> google.protobuf.Empty
	22, // 31: bedrock.metaserver.MetaService.GetShardRoutes:output_type -> bedrock.metaserver.GetShardRoutesResponse
	7,  // 32: bedrock.metaserver.MetaService.CreateStorage:output_type -> bedrock.metaserver.CreateStorageResponse
	9,  // 33: bedrock.metaserver.MetaService.DeleteStorage:output_type -> bedrock.metaserver.DeleteStorageResponse
	11, // 34: bedrock.metaserver.MetaService.UndeleteStorage:output_type -> bedrock.metaserver.UndeleteStorageResponse
	13, // 35: bedrock.metaserver.MetaService.RenameStorage:output_type -> bedrock.metaserver.RenameStorageResponse
	15, // 36: bedrock.metaserver.MetaService.ResizeStorage:output_type -> bedrock.metaserver.ResizeStorageResponse
	17, // 37: bedrock.metaserver.MetaService.GetStorages:output_type -> bedrock.metaserver.GetStoragesResponse
	26, // 38: bedrock.metaserver.MetaService.AddDataServer:output_type -> bedrock.metaserver.AddDataServerResponse
	28, // 39: bedrock.metaserver.MetaService.RemoveDataServer:output_type -> bedrock.metaserver.RemoveDataServerResponse
	30, // 40: bedrock.metaserver.MetaService.ListDataServer:output_type -> bedrock.metaserver.ListDataServerResponse
	32, // 41: bedrock.metaserver.MetaService.UpdateDataServer:output_type -> bedrock.metaserver.UpdateDataServerResponse
	34, // 42: bedrock.metaserver.MetaService.ShardInfo:output_type -> bedrock.metaserver.ShardInfoResponse
	30, // [30:43] is the sub-list for method output_type
	17, // [17:30] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_metaserver_proto_init() }
func file_metaserver_proto_init() {
	if File_metaserver_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_metaserver_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Storage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metaserver_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Shard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metaserver_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataServer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metaserver_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Replicate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metaserver_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartBeatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metaserver_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartBeatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metaserver_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateStorageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metaserver_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateStorageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metaserver_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteStorageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metaserver_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteStorageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metaserver_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UndeleteStorageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metaserver_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UndeleteStorageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metaserver_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RenameStorageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metaserver_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RenameStorageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metaserver_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResizeStorageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metaserver_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResizeStorageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metaserver_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStoragesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metaserver_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStoragesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metaserver_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShardRange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metaserver_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RouteRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metaserver_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShardList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metaserver_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetShardRoutesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metaserver_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetShardRoutesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metaserver_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetShardRoutesByStorageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metaserver_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetShardRoutesByStorageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metaserver_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddDataServerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metaserver_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddDataServerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metaserver_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveDataServerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metaserver_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveDataServerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metaserver_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDataServerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metaserver_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDataServerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metaserver_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDataServerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metaserver_proto_msgTypes[32].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDataServerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metaserver_proto_msgTypes[33].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShardInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metaserver_proto_msgTypes[34].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShardInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_metaserver_proto_msgTypes[21].OneofWrappers = []interface{}{
		(*GetShardRoutesRequest_ShardsList)(nil),
		(*GetShardRoutesRequest_ShardRange)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_metaserver_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metaserver_proto_goTypes,
		DependencyIndexes: file_metaserver_proto_depIdxs,
		MessageInfos:      file_metaserver_proto_msgTypes,
	}.Build()
	File_metaserver_proto = out.File
	file_metaserver_proto_rawDesc = nil
	file_metaserver_proto_goTypes = nil
	file_metaserver_proto_depIdxs = nil
}
