// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proxy.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_proxy_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_proxy_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021005 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/service.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_proxy_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_proxy_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_proxy_2eproto;
namespace bedrock {
namespace proxy {
class BedRockKvDeleteRequest;
struct BedRockKvDeleteRequestDefaultTypeInternal;
extern BedRockKvDeleteRequestDefaultTypeInternal _BedRockKvDeleteRequest_default_instance_;
class BedRockKvDeleteResponse;
struct BedRockKvDeleteResponseDefaultTypeInternal;
extern BedRockKvDeleteResponseDefaultTypeInternal _BedRockKvDeleteResponse_default_instance_;
class BedRockKvGetRequest;
struct BedRockKvGetRequestDefaultTypeInternal;
extern BedRockKvGetRequestDefaultTypeInternal _BedRockKvGetRequest_default_instance_;
class BedRockKvGetResponse;
struct BedRockKvGetResponseDefaultTypeInternal;
extern BedRockKvGetResponseDefaultTypeInternal _BedRockKvGetResponse_default_instance_;
class BedRockKvSetRequest;
struct BedRockKvSetRequestDefaultTypeInternal;
extern BedRockKvSetRequestDefaultTypeInternal _BedRockKvSetRequest_default_instance_;
class BedRockKvSetResponse;
struct BedRockKvSetResponseDefaultTypeInternal;
extern BedRockKvSetResponseDefaultTypeInternal _BedRockKvSetResponse_default_instance_;
}  // namespace proxy
}  // namespace bedrock
PROTOBUF_NAMESPACE_OPEN
template<> ::bedrock::proxy::BedRockKvDeleteRequest* Arena::CreateMaybeMessage<::bedrock::proxy::BedRockKvDeleteRequest>(Arena*);
template<> ::bedrock::proxy::BedRockKvDeleteResponse* Arena::CreateMaybeMessage<::bedrock::proxy::BedRockKvDeleteResponse>(Arena*);
template<> ::bedrock::proxy::BedRockKvGetRequest* Arena::CreateMaybeMessage<::bedrock::proxy::BedRockKvGetRequest>(Arena*);
template<> ::bedrock::proxy::BedRockKvGetResponse* Arena::CreateMaybeMessage<::bedrock::proxy::BedRockKvGetResponse>(Arena*);
template<> ::bedrock::proxy::BedRockKvSetRequest* Arena::CreateMaybeMessage<::bedrock::proxy::BedRockKvSetRequest>(Arena*);
template<> ::bedrock::proxy::BedRockKvSetResponse* Arena::CreateMaybeMessage<::bedrock::proxy::BedRockKvSetResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace bedrock {
namespace proxy {

enum Error : int {
  OK = 0,
  NO_SUCH_KEY = 1,
  INVLIAD_PARAMETERS = 2,
  UNKNOWN = 255,
  Error_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  Error_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool Error_IsValid(int value);
constexpr Error Error_MIN = OK;
constexpr Error Error_MAX = UNKNOWN;
constexpr int Error_ARRAYSIZE = Error_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Error_descriptor();
template<typename T>
inline const std::string& Error_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Error>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Error_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Error_descriptor(), enum_t_value);
}
inline bool Error_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Error* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Error>(
    Error_descriptor(), name, value);
}
// ===================================================================

class BedRockKvGetRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:bedrock.proxy.BedRockKvGetRequest) */ {
 public:
  inline BedRockKvGetRequest() : BedRockKvGetRequest(nullptr) {}
  ~BedRockKvGetRequest() override;
  explicit PROTOBUF_CONSTEXPR BedRockKvGetRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  BedRockKvGetRequest(const BedRockKvGetRequest& from);
  BedRockKvGetRequest(BedRockKvGetRequest&& from) noexcept
    : BedRockKvGetRequest() {
    *this = ::std::move(from);
  }

  inline BedRockKvGetRequest& operator=(const BedRockKvGetRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline BedRockKvGetRequest& operator=(BedRockKvGetRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BedRockKvGetRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const BedRockKvGetRequest* internal_default_instance() {
    return reinterpret_cast<const BedRockKvGetRequest*>(
               &_BedRockKvGetRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(BedRockKvGetRequest& a, BedRockKvGetRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(BedRockKvGetRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BedRockKvGetRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BedRockKvGetRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<BedRockKvGetRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const BedRockKvGetRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const BedRockKvGetRequest& from) {
    BedRockKvGetRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BedRockKvGetRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "bedrock.proxy.BedRockKvGetRequest";
  }
  protected:
  explicit BedRockKvGetRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kKeyFieldNumber = 2,
    kStorageIdFieldNumber = 1,
  };
  // bytes key = 2;
  void clear_key();
  const std::string& key() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_key(ArgT0&& arg0, ArgT... args);
  std::string* mutable_key();
  PROTOBUF_NODISCARD std::string* release_key();
  void set_allocated_key(std::string* key);
  private:
  const std::string& _internal_key() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_key(const std::string& value);
  std::string* _internal_mutable_key();
  public:

  // uint32 storage_id = 1;
  void clear_storage_id();
  uint32_t storage_id() const;
  void set_storage_id(uint32_t value);
  private:
  uint32_t _internal_storage_id() const;
  void _internal_set_storage_id(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:bedrock.proxy.BedRockKvGetRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr key_;
    uint32_t storage_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proxy_2eproto;
};
// -------------------------------------------------------------------

class BedRockKvGetResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:bedrock.proxy.BedRockKvGetResponse) */ {
 public:
  inline BedRockKvGetResponse() : BedRockKvGetResponse(nullptr) {}
  ~BedRockKvGetResponse() override;
  explicit PROTOBUF_CONSTEXPR BedRockKvGetResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  BedRockKvGetResponse(const BedRockKvGetResponse& from);
  BedRockKvGetResponse(BedRockKvGetResponse&& from) noexcept
    : BedRockKvGetResponse() {
    *this = ::std::move(from);
  }

  inline BedRockKvGetResponse& operator=(const BedRockKvGetResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline BedRockKvGetResponse& operator=(BedRockKvGetResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BedRockKvGetResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const BedRockKvGetResponse* internal_default_instance() {
    return reinterpret_cast<const BedRockKvGetResponse*>(
               &_BedRockKvGetResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(BedRockKvGetResponse& a, BedRockKvGetResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(BedRockKvGetResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BedRockKvGetResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BedRockKvGetResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<BedRockKvGetResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const BedRockKvGetResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const BedRockKvGetResponse& from) {
    BedRockKvGetResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BedRockKvGetResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "bedrock.proxy.BedRockKvGetResponse";
  }
  protected:
  explicit BedRockKvGetResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kValueFieldNumber = 1,
    kErrFieldNumber = 255,
  };
  // bytes value = 1;
  void clear_value();
  const std::string& value() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_value(ArgT0&& arg0, ArgT... args);
  std::string* mutable_value();
  PROTOBUF_NODISCARD std::string* release_value();
  void set_allocated_value(std::string* value);
  private:
  const std::string& _internal_value() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_value(const std::string& value);
  std::string* _internal_mutable_value();
  public:

  // .bedrock.proxy.Error err = 255;
  void clear_err();
  ::bedrock::proxy::Error err() const;
  void set_err(::bedrock::proxy::Error value);
  private:
  ::bedrock::proxy::Error _internal_err() const;
  void _internal_set_err(::bedrock::proxy::Error value);
  public:

  // @@protoc_insertion_point(class_scope:bedrock.proxy.BedRockKvGetResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr value_;
    int err_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proxy_2eproto;
};
// -------------------------------------------------------------------

class BedRockKvSetRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:bedrock.proxy.BedRockKvSetRequest) */ {
 public:
  inline BedRockKvSetRequest() : BedRockKvSetRequest(nullptr) {}
  ~BedRockKvSetRequest() override;
  explicit PROTOBUF_CONSTEXPR BedRockKvSetRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  BedRockKvSetRequest(const BedRockKvSetRequest& from);
  BedRockKvSetRequest(BedRockKvSetRequest&& from) noexcept
    : BedRockKvSetRequest() {
    *this = ::std::move(from);
  }

  inline BedRockKvSetRequest& operator=(const BedRockKvSetRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline BedRockKvSetRequest& operator=(BedRockKvSetRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BedRockKvSetRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const BedRockKvSetRequest* internal_default_instance() {
    return reinterpret_cast<const BedRockKvSetRequest*>(
               &_BedRockKvSetRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(BedRockKvSetRequest& a, BedRockKvSetRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(BedRockKvSetRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BedRockKvSetRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BedRockKvSetRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<BedRockKvSetRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const BedRockKvSetRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const BedRockKvSetRequest& from) {
    BedRockKvSetRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BedRockKvSetRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "bedrock.proxy.BedRockKvSetRequest";
  }
  protected:
  explicit BedRockKvSetRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kKeyFieldNumber = 2,
    kValueFieldNumber = 3,
    kStorageIdFieldNumber = 1,
  };
  // bytes key = 2;
  void clear_key();
  const std::string& key() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_key(ArgT0&& arg0, ArgT... args);
  std::string* mutable_key();
  PROTOBUF_NODISCARD std::string* release_key();
  void set_allocated_key(std::string* key);
  private:
  const std::string& _internal_key() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_key(const std::string& value);
  std::string* _internal_mutable_key();
  public:

  // bytes value = 3;
  void clear_value();
  const std::string& value() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_value(ArgT0&& arg0, ArgT... args);
  std::string* mutable_value();
  PROTOBUF_NODISCARD std::string* release_value();
  void set_allocated_value(std::string* value);
  private:
  const std::string& _internal_value() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_value(const std::string& value);
  std::string* _internal_mutable_value();
  public:

  // uint32 storage_id = 1;
  void clear_storage_id();
  uint32_t storage_id() const;
  void set_storage_id(uint32_t value);
  private:
  uint32_t _internal_storage_id() const;
  void _internal_set_storage_id(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:bedrock.proxy.BedRockKvSetRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr key_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr value_;
    uint32_t storage_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proxy_2eproto;
};
// -------------------------------------------------------------------

class BedRockKvSetResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:bedrock.proxy.BedRockKvSetResponse) */ {
 public:
  inline BedRockKvSetResponse() : BedRockKvSetResponse(nullptr) {}
  ~BedRockKvSetResponse() override;
  explicit PROTOBUF_CONSTEXPR BedRockKvSetResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  BedRockKvSetResponse(const BedRockKvSetResponse& from);
  BedRockKvSetResponse(BedRockKvSetResponse&& from) noexcept
    : BedRockKvSetResponse() {
    *this = ::std::move(from);
  }

  inline BedRockKvSetResponse& operator=(const BedRockKvSetResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline BedRockKvSetResponse& operator=(BedRockKvSetResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BedRockKvSetResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const BedRockKvSetResponse* internal_default_instance() {
    return reinterpret_cast<const BedRockKvSetResponse*>(
               &_BedRockKvSetResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(BedRockKvSetResponse& a, BedRockKvSetResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(BedRockKvSetResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BedRockKvSetResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BedRockKvSetResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<BedRockKvSetResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const BedRockKvSetResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const BedRockKvSetResponse& from) {
    BedRockKvSetResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BedRockKvSetResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "bedrock.proxy.BedRockKvSetResponse";
  }
  protected:
  explicit BedRockKvSetResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kErrFieldNumber = 255,
  };
  // .bedrock.proxy.Error err = 255;
  void clear_err();
  ::bedrock::proxy::Error err() const;
  void set_err(::bedrock::proxy::Error value);
  private:
  ::bedrock::proxy::Error _internal_err() const;
  void _internal_set_err(::bedrock::proxy::Error value);
  public:

  // @@protoc_insertion_point(class_scope:bedrock.proxy.BedRockKvSetResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int err_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proxy_2eproto;
};
// -------------------------------------------------------------------

class BedRockKvDeleteRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:bedrock.proxy.BedRockKvDeleteRequest) */ {
 public:
  inline BedRockKvDeleteRequest() : BedRockKvDeleteRequest(nullptr) {}
  ~BedRockKvDeleteRequest() override;
  explicit PROTOBUF_CONSTEXPR BedRockKvDeleteRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  BedRockKvDeleteRequest(const BedRockKvDeleteRequest& from);
  BedRockKvDeleteRequest(BedRockKvDeleteRequest&& from) noexcept
    : BedRockKvDeleteRequest() {
    *this = ::std::move(from);
  }

  inline BedRockKvDeleteRequest& operator=(const BedRockKvDeleteRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline BedRockKvDeleteRequest& operator=(BedRockKvDeleteRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BedRockKvDeleteRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const BedRockKvDeleteRequest* internal_default_instance() {
    return reinterpret_cast<const BedRockKvDeleteRequest*>(
               &_BedRockKvDeleteRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(BedRockKvDeleteRequest& a, BedRockKvDeleteRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(BedRockKvDeleteRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BedRockKvDeleteRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BedRockKvDeleteRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<BedRockKvDeleteRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const BedRockKvDeleteRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const BedRockKvDeleteRequest& from) {
    BedRockKvDeleteRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BedRockKvDeleteRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "bedrock.proxy.BedRockKvDeleteRequest";
  }
  protected:
  explicit BedRockKvDeleteRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kKeyFieldNumber = 2,
    kStorageIdFieldNumber = 1,
  };
  // bytes key = 2;
  void clear_key();
  const std::string& key() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_key(ArgT0&& arg0, ArgT... args);
  std::string* mutable_key();
  PROTOBUF_NODISCARD std::string* release_key();
  void set_allocated_key(std::string* key);
  private:
  const std::string& _internal_key() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_key(const std::string& value);
  std::string* _internal_mutable_key();
  public:

  // uint32 storage_id = 1;
  void clear_storage_id();
  uint32_t storage_id() const;
  void set_storage_id(uint32_t value);
  private:
  uint32_t _internal_storage_id() const;
  void _internal_set_storage_id(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:bedrock.proxy.BedRockKvDeleteRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr key_;
    uint32_t storage_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proxy_2eproto;
};
// -------------------------------------------------------------------

class BedRockKvDeleteResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:bedrock.proxy.BedRockKvDeleteResponse) */ {
 public:
  inline BedRockKvDeleteResponse() : BedRockKvDeleteResponse(nullptr) {}
  ~BedRockKvDeleteResponse() override;
  explicit PROTOBUF_CONSTEXPR BedRockKvDeleteResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  BedRockKvDeleteResponse(const BedRockKvDeleteResponse& from);
  BedRockKvDeleteResponse(BedRockKvDeleteResponse&& from) noexcept
    : BedRockKvDeleteResponse() {
    *this = ::std::move(from);
  }

  inline BedRockKvDeleteResponse& operator=(const BedRockKvDeleteResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline BedRockKvDeleteResponse& operator=(BedRockKvDeleteResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BedRockKvDeleteResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const BedRockKvDeleteResponse* internal_default_instance() {
    return reinterpret_cast<const BedRockKvDeleteResponse*>(
               &_BedRockKvDeleteResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(BedRockKvDeleteResponse& a, BedRockKvDeleteResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(BedRockKvDeleteResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BedRockKvDeleteResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BedRockKvDeleteResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<BedRockKvDeleteResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const BedRockKvDeleteResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const BedRockKvDeleteResponse& from) {
    BedRockKvDeleteResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BedRockKvDeleteResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "bedrock.proxy.BedRockKvDeleteResponse";
  }
  protected:
  explicit BedRockKvDeleteResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kErrFieldNumber = 255,
  };
  // .bedrock.proxy.Error err = 255;
  void clear_err();
  ::bedrock::proxy::Error err() const;
  void set_err(::bedrock::proxy::Error value);
  private:
  ::bedrock::proxy::Error _internal_err() const;
  void _internal_set_err(::bedrock::proxy::Error value);
  public:

  // @@protoc_insertion_point(class_scope:bedrock.proxy.BedRockKvDeleteResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int err_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proxy_2eproto;
};
// ===================================================================

class ProxyService_Stub;

class ProxyService : public ::PROTOBUF_NAMESPACE_ID::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline ProxyService() {};
 public:
  virtual ~ProxyService();

  typedef ProxyService_Stub Stub;

  static const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* descriptor();

  virtual void BedRockKvSet(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::bedrock::proxy::BedRockKvSetRequest* request,
                       ::bedrock::proxy::BedRockKvSetResponse* response,
                       ::google::protobuf::Closure* done);
  virtual void BedRockKvGet(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::bedrock::proxy::BedRockKvGetRequest* request,
                       ::bedrock::proxy::BedRockKvGetResponse* response,
                       ::google::protobuf::Closure* done);
  virtual void BedRockKvDelete(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::bedrock::proxy::BedRockKvDeleteRequest* request,
                       ::bedrock::proxy::BedRockKvDeleteResponse* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method,
                  ::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                  const ::PROTOBUF_NAMESPACE_ID::Message* request,
                  ::PROTOBUF_NAMESPACE_ID::Message* response,
                  ::google::protobuf::Closure* done);
  const ::PROTOBUF_NAMESPACE_ID::Message& GetRequestPrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;
  const ::PROTOBUF_NAMESPACE_ID::Message& GetResponsePrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(ProxyService);
};

class ProxyService_Stub : public ProxyService {
 public:
  ProxyService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel);
  ProxyService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel,
                   ::PROTOBUF_NAMESPACE_ID::Service::ChannelOwnership ownership);
  ~ProxyService_Stub();

  inline ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel() { return channel_; }

  // implements ProxyService ------------------------------------------

  void BedRockKvSet(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::bedrock::proxy::BedRockKvSetRequest* request,
                       ::bedrock::proxy::BedRockKvSetResponse* response,
                       ::google::protobuf::Closure* done);
  void BedRockKvGet(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::bedrock::proxy::BedRockKvGetRequest* request,
                       ::bedrock::proxy::BedRockKvGetResponse* response,
                       ::google::protobuf::Closure* done);
  void BedRockKvDelete(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::bedrock::proxy::BedRockKvDeleteRequest* request,
                       ::bedrock::proxy::BedRockKvDeleteResponse* response,
                       ::google::protobuf::Closure* done);
 private:
  ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(ProxyService_Stub);
};


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// BedRockKvGetRequest

// uint32 storage_id = 1;
inline void BedRockKvGetRequest::clear_storage_id() {
  _impl_.storage_id_ = 0u;
}
inline uint32_t BedRockKvGetRequest::_internal_storage_id() const {
  return _impl_.storage_id_;
}
inline uint32_t BedRockKvGetRequest::storage_id() const {
  // @@protoc_insertion_point(field_get:bedrock.proxy.BedRockKvGetRequest.storage_id)
  return _internal_storage_id();
}
inline void BedRockKvGetRequest::_internal_set_storage_id(uint32_t value) {
  
  _impl_.storage_id_ = value;
}
inline void BedRockKvGetRequest::set_storage_id(uint32_t value) {
  _internal_set_storage_id(value);
  // @@protoc_insertion_point(field_set:bedrock.proxy.BedRockKvGetRequest.storage_id)
}

// bytes key = 2;
inline void BedRockKvGetRequest::clear_key() {
  _impl_.key_.ClearToEmpty();
}
inline const std::string& BedRockKvGetRequest::key() const {
  // @@protoc_insertion_point(field_get:bedrock.proxy.BedRockKvGetRequest.key)
  return _internal_key();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void BedRockKvGetRequest::set_key(ArgT0&& arg0, ArgT... args) {
 
 _impl_.key_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:bedrock.proxy.BedRockKvGetRequest.key)
}
inline std::string* BedRockKvGetRequest::mutable_key() {
  std::string* _s = _internal_mutable_key();
  // @@protoc_insertion_point(field_mutable:bedrock.proxy.BedRockKvGetRequest.key)
  return _s;
}
inline const std::string& BedRockKvGetRequest::_internal_key() const {
  return _impl_.key_.Get();
}
inline void BedRockKvGetRequest::_internal_set_key(const std::string& value) {
  
  _impl_.key_.Set(value, GetArenaForAllocation());
}
inline std::string* BedRockKvGetRequest::_internal_mutable_key() {
  
  return _impl_.key_.Mutable(GetArenaForAllocation());
}
inline std::string* BedRockKvGetRequest::release_key() {
  // @@protoc_insertion_point(field_release:bedrock.proxy.BedRockKvGetRequest.key)
  return _impl_.key_.Release();
}
inline void BedRockKvGetRequest::set_allocated_key(std::string* key) {
  if (key != nullptr) {
    
  } else {
    
  }
  _impl_.key_.SetAllocated(key, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.key_.IsDefault()) {
    _impl_.key_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:bedrock.proxy.BedRockKvGetRequest.key)
}

// -------------------------------------------------------------------

// BedRockKvGetResponse

// bytes value = 1;
inline void BedRockKvGetResponse::clear_value() {
  _impl_.value_.ClearToEmpty();
}
inline const std::string& BedRockKvGetResponse::value() const {
  // @@protoc_insertion_point(field_get:bedrock.proxy.BedRockKvGetResponse.value)
  return _internal_value();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void BedRockKvGetResponse::set_value(ArgT0&& arg0, ArgT... args) {
 
 _impl_.value_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:bedrock.proxy.BedRockKvGetResponse.value)
}
inline std::string* BedRockKvGetResponse::mutable_value() {
  std::string* _s = _internal_mutable_value();
  // @@protoc_insertion_point(field_mutable:bedrock.proxy.BedRockKvGetResponse.value)
  return _s;
}
inline const std::string& BedRockKvGetResponse::_internal_value() const {
  return _impl_.value_.Get();
}
inline void BedRockKvGetResponse::_internal_set_value(const std::string& value) {
  
  _impl_.value_.Set(value, GetArenaForAllocation());
}
inline std::string* BedRockKvGetResponse::_internal_mutable_value() {
  
  return _impl_.value_.Mutable(GetArenaForAllocation());
}
inline std::string* BedRockKvGetResponse::release_value() {
  // @@protoc_insertion_point(field_release:bedrock.proxy.BedRockKvGetResponse.value)
  return _impl_.value_.Release();
}
inline void BedRockKvGetResponse::set_allocated_value(std::string* value) {
  if (value != nullptr) {
    
  } else {
    
  }
  _impl_.value_.SetAllocated(value, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.value_.IsDefault()) {
    _impl_.value_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:bedrock.proxy.BedRockKvGetResponse.value)
}

// .bedrock.proxy.Error err = 255;
inline void BedRockKvGetResponse::clear_err() {
  _impl_.err_ = 0;
}
inline ::bedrock::proxy::Error BedRockKvGetResponse::_internal_err() const {
  return static_cast< ::bedrock::proxy::Error >(_impl_.err_);
}
inline ::bedrock::proxy::Error BedRockKvGetResponse::err() const {
  // @@protoc_insertion_point(field_get:bedrock.proxy.BedRockKvGetResponse.err)
  return _internal_err();
}
inline void BedRockKvGetResponse::_internal_set_err(::bedrock::proxy::Error value) {
  
  _impl_.err_ = value;
}
inline void BedRockKvGetResponse::set_err(::bedrock::proxy::Error value) {
  _internal_set_err(value);
  // @@protoc_insertion_point(field_set:bedrock.proxy.BedRockKvGetResponse.err)
}

// -------------------------------------------------------------------

// BedRockKvSetRequest

// uint32 storage_id = 1;
inline void BedRockKvSetRequest::clear_storage_id() {
  _impl_.storage_id_ = 0u;
}
inline uint32_t BedRockKvSetRequest::_internal_storage_id() const {
  return _impl_.storage_id_;
}
inline uint32_t BedRockKvSetRequest::storage_id() const {
  // @@protoc_insertion_point(field_get:bedrock.proxy.BedRockKvSetRequest.storage_id)
  return _internal_storage_id();
}
inline void BedRockKvSetRequest::_internal_set_storage_id(uint32_t value) {
  
  _impl_.storage_id_ = value;
}
inline void BedRockKvSetRequest::set_storage_id(uint32_t value) {
  _internal_set_storage_id(value);
  // @@protoc_insertion_point(field_set:bedrock.proxy.BedRockKvSetRequest.storage_id)
}

// bytes key = 2;
inline void BedRockKvSetRequest::clear_key() {
  _impl_.key_.ClearToEmpty();
}
inline const std::string& BedRockKvSetRequest::key() const {
  // @@protoc_insertion_point(field_get:bedrock.proxy.BedRockKvSetRequest.key)
  return _internal_key();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void BedRockKvSetRequest::set_key(ArgT0&& arg0, ArgT... args) {
 
 _impl_.key_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:bedrock.proxy.BedRockKvSetRequest.key)
}
inline std::string* BedRockKvSetRequest::mutable_key() {
  std::string* _s = _internal_mutable_key();
  // @@protoc_insertion_point(field_mutable:bedrock.proxy.BedRockKvSetRequest.key)
  return _s;
}
inline const std::string& BedRockKvSetRequest::_internal_key() const {
  return _impl_.key_.Get();
}
inline void BedRockKvSetRequest::_internal_set_key(const std::string& value) {
  
  _impl_.key_.Set(value, GetArenaForAllocation());
}
inline std::string* BedRockKvSetRequest::_internal_mutable_key() {
  
  return _impl_.key_.Mutable(GetArenaForAllocation());
}
inline std::string* BedRockKvSetRequest::release_key() {
  // @@protoc_insertion_point(field_release:bedrock.proxy.BedRockKvSetRequest.key)
  return _impl_.key_.Release();
}
inline void BedRockKvSetRequest::set_allocated_key(std::string* key) {
  if (key != nullptr) {
    
  } else {
    
  }
  _impl_.key_.SetAllocated(key, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.key_.IsDefault()) {
    _impl_.key_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:bedrock.proxy.BedRockKvSetRequest.key)
}

// bytes value = 3;
inline void BedRockKvSetRequest::clear_value() {
  _impl_.value_.ClearToEmpty();
}
inline const std::string& BedRockKvSetRequest::value() const {
  // @@protoc_insertion_point(field_get:bedrock.proxy.BedRockKvSetRequest.value)
  return _internal_value();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void BedRockKvSetRequest::set_value(ArgT0&& arg0, ArgT... args) {
 
 _impl_.value_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:bedrock.proxy.BedRockKvSetRequest.value)
}
inline std::string* BedRockKvSetRequest::mutable_value() {
  std::string* _s = _internal_mutable_value();
  // @@protoc_insertion_point(field_mutable:bedrock.proxy.BedRockKvSetRequest.value)
  return _s;
}
inline const std::string& BedRockKvSetRequest::_internal_value() const {
  return _impl_.value_.Get();
}
inline void BedRockKvSetRequest::_internal_set_value(const std::string& value) {
  
  _impl_.value_.Set(value, GetArenaForAllocation());
}
inline std::string* BedRockKvSetRequest::_internal_mutable_value() {
  
  return _impl_.value_.Mutable(GetArenaForAllocation());
}
inline std::string* BedRockKvSetRequest::release_value() {
  // @@protoc_insertion_point(field_release:bedrock.proxy.BedRockKvSetRequest.value)
  return _impl_.value_.Release();
}
inline void BedRockKvSetRequest::set_allocated_value(std::string* value) {
  if (value != nullptr) {
    
  } else {
    
  }
  _impl_.value_.SetAllocated(value, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.value_.IsDefault()) {
    _impl_.value_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:bedrock.proxy.BedRockKvSetRequest.value)
}

// -------------------------------------------------------------------

// BedRockKvSetResponse

// .bedrock.proxy.Error err = 255;
inline void BedRockKvSetResponse::clear_err() {
  _impl_.err_ = 0;
}
inline ::bedrock::proxy::Error BedRockKvSetResponse::_internal_err() const {
  return static_cast< ::bedrock::proxy::Error >(_impl_.err_);
}
inline ::bedrock::proxy::Error BedRockKvSetResponse::err() const {
  // @@protoc_insertion_point(field_get:bedrock.proxy.BedRockKvSetResponse.err)
  return _internal_err();
}
inline void BedRockKvSetResponse::_internal_set_err(::bedrock::proxy::Error value) {
  
  _impl_.err_ = value;
}
inline void BedRockKvSetResponse::set_err(::bedrock::proxy::Error value) {
  _internal_set_err(value);
  // @@protoc_insertion_point(field_set:bedrock.proxy.BedRockKvSetResponse.err)
}

// -------------------------------------------------------------------

// BedRockKvDeleteRequest

// uint32 storage_id = 1;
inline void BedRockKvDeleteRequest::clear_storage_id() {
  _impl_.storage_id_ = 0u;
}
inline uint32_t BedRockKvDeleteRequest::_internal_storage_id() const {
  return _impl_.storage_id_;
}
inline uint32_t BedRockKvDeleteRequest::storage_id() const {
  // @@protoc_insertion_point(field_get:bedrock.proxy.BedRockKvDeleteRequest.storage_id)
  return _internal_storage_id();
}
inline void BedRockKvDeleteRequest::_internal_set_storage_id(uint32_t value) {
  
  _impl_.storage_id_ = value;
}
inline void BedRockKvDeleteRequest::set_storage_id(uint32_t value) {
  _internal_set_storage_id(value);
  // @@protoc_insertion_point(field_set:bedrock.proxy.BedRockKvDeleteRequest.storage_id)
}

// bytes key = 2;
inline void BedRockKvDeleteRequest::clear_key() {
  _impl_.key_.ClearToEmpty();
}
inline const std::string& BedRockKvDeleteRequest::key() const {
  // @@protoc_insertion_point(field_get:bedrock.proxy.BedRockKvDeleteRequest.key)
  return _internal_key();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void BedRockKvDeleteRequest::set_key(ArgT0&& arg0, ArgT... args) {
 
 _impl_.key_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:bedrock.proxy.BedRockKvDeleteRequest.key)
}
inline std::string* BedRockKvDeleteRequest::mutable_key() {
  std::string* _s = _internal_mutable_key();
  // @@protoc_insertion_point(field_mutable:bedrock.proxy.BedRockKvDeleteRequest.key)
  return _s;
}
inline const std::string& BedRockKvDeleteRequest::_internal_key() const {
  return _impl_.key_.Get();
}
inline void BedRockKvDeleteRequest::_internal_set_key(const std::string& value) {
  
  _impl_.key_.Set(value, GetArenaForAllocation());
}
inline std::string* BedRockKvDeleteRequest::_internal_mutable_key() {
  
  return _impl_.key_.Mutable(GetArenaForAllocation());
}
inline std::string* BedRockKvDeleteRequest::release_key() {
  // @@protoc_insertion_point(field_release:bedrock.proxy.BedRockKvDeleteRequest.key)
  return _impl_.key_.Release();
}
inline void BedRockKvDeleteRequest::set_allocated_key(std::string* key) {
  if (key != nullptr) {
    
  } else {
    
  }
  _impl_.key_.SetAllocated(key, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.key_.IsDefault()) {
    _impl_.key_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:bedrock.proxy.BedRockKvDeleteRequest.key)
}

// -------------------------------------------------------------------

// BedRockKvDeleteResponse

// .bedrock.proxy.Error err = 255;
inline void BedRockKvDeleteResponse::clear_err() {
  _impl_.err_ = 0;
}
inline ::bedrock::proxy::Error BedRockKvDeleteResponse::_internal_err() const {
  return static_cast< ::bedrock::proxy::Error >(_impl_.err_);
}
inline ::bedrock::proxy::Error BedRockKvDeleteResponse::err() const {
  // @@protoc_insertion_point(field_get:bedrock.proxy.BedRockKvDeleteResponse.err)
  return _internal_err();
}
inline void BedRockKvDeleteResponse::_internal_set_err(::bedrock::proxy::Error value) {
  
  _impl_.err_ = value;
}
inline void BedRockKvDeleteResponse::set_err(::bedrock::proxy::Error value) {
  _internal_set_err(value);
  // @@protoc_insertion_point(field_set:bedrock.proxy.BedRockKvDeleteResponse.err)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace proxy
}  // namespace bedrock

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::bedrock::proxy::Error> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::bedrock::proxy::Error>() {
  return ::bedrock::proxy::Error_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_proxy_2eproto
